In [146]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [110]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [111]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
# 케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야하므로 미리 +1 선언 
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [113]:
t.word_index

{'말이': 1,
 '경마장에': 2,
 '있는': 3,
 '뛰고': 4,
 '있다': 5,
 '그의': 6,
 '법이다': 7,
 '가는': 8,
 '고와야': 9,
 '오는': 10,
 '곱다': 11}

In [109]:
t.fit_on_texts([text])

In [4]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [247]:
text1 = """
잦동충은 유충때부터 가스라이팅해서 기 눌러놔야됨  잦동충 있는년들 띵잦이 많긔 앰앱한테 가스라이팅 당함  잦동생 한명 있는데 어릴때부터 가스라이팅 시켰더니 긔  잘생긴 잦 묶어놓고 존나패고 가스라이팅하고싶으면 이상성욕이긔  나래코기랑 도연언냐는 나래코기가 가스라이팅한거긔  몇백년동안 가스라이팅 당한 한녀 불쌍해  머학 새내기때 가스라이팅 당하기 존나 쉬워   전래동화라면서 좆기때부터 가스라이팅시키노  토마토 가스라이팅 당한 거 맞지  봊초년들특징이 그냥 팩트말하면 가스라이팅이라함  와 가스라이팅 가스라이팅 말만 듣고 뜻만 알았지  족구 군대간 년동안 가축들이 가스라이팅 당함  봉준이방송은 가스라이팅방송임  지금 케이는 가스라이팅 중임  딱 여자들이 좋아하는 단어 가스라이팅 오지게 당한거지 푸르는  최군은 가스라이팅 잘하지  사실 방송 별거 아닌데 혜디주변에서 혜디 가스라이팅하는게 참  어릴때부터 가스라이팅 당해서 자존감 하나도 없어  개딱단과 개엑이야 말로 가스라이팅 한거긔  김극라는 가스라이팅하는 봊 만나야해  혹시 공주 가스라이팅 당한거 아닐까윤  저 말한 놈 그단톡방에서 가스라이팅 당한거같긔  여니 잇팁인데 가스라이팅이라는 단어 이해안됨  뿡힛 가스라이팅이 믹테야 적어도 보컬한테는  씹매들시대엔 봊기때부터 가스라이팅해서 살때  중딩때 나한테 오지게 가스라이팅한년 죽이고싶어  빻다빠는년들 가스라이팅 잘당할것같긔  현실에서 가스라이팅 병신끼리 주고받지 않노  가스라이팅 당하고살긔  하 시발 가스라이팅 인 새끼 있는데  나 가스라이팅 존나 당함  누가 나 가스라이팅 시도한적 없긔  는 가스라이팅 절대 안당함  가스라이팅 문장 저거 한남들 단골멘트 아니긔  한남한테 가스라이팅하면 한남이 나한테 의지해서  한남한테 가스라이팅해보고싶노  띠닌 인데 가스라이팅 이해가긔  가스라이팅 이해 안가는 언냐  잇팁 가스라이팅 이해 안간다는거 딱 한남같노   인데 가스라이팅 당하는거 존나 이해안가긔  발삼이 잦스틴이 가스라이팅 시켜놨으니까 놔줘  한남 좃 웃긴거 누가 널 만나주냐는 식으로 가스라이팅하면서  한녀들은 한남 존나싫다는데 왤케 가스라이팅하는거노  라도춤은 뿡힛식 강제 가스라이팅이지 라도춤이 어디서  망망프다이어리 녕동민 가스라이팅 너무당해서  스시잦들 투잡가스라이팅대리효도없는것만으로도 라고 생각했었는데  한녀들이 당한 역대급 가스라이팅은 반일선동이라고 생각해  황발삼 가스라이팅 하고싶어  빅히트가 개인방 몇명만 준거 가스라이팅 이긔  의새도 환자 가스라이팅 하는 의새 개많아  미동이가 윾나 가스라이팅하려는거같애서 놈 혐오스럽긔  가스라이팅 단어도 변질됨  잦친한테 자격지심들고 가스라이팅 당한거 생각하면 노무 분해  빻다 옆에서 못생겼다고 가스라이팅 시킬 봊이 필요함  메리는 가스라이팅 안통할 것 같긔  강섹훈 가스라이팅 존나 시키고 싶긔  나 감쓰삼고 가스라이팅하던 틀딱년들 손절했는데  혐애할때 유독 한녀들만 가스라이팅 존나당하는거 같긔  득팔이 노무 못생겼기도 하고 주변에서 가스라이팅 많이 당했을긋  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  진심 성형 보편화 된거 한남 가스라이팅 아니노  봊친한테 휘둘리며 가스라이팅 당하는 딘쿵야  녀살려야 아메한테 가스라이팅 그만해  가스라이팅 당한 봊자식은 사실 제대로 반항도 못해  이런갤열면 앰생한남들 기어들어와서 가스라이팅 시작함  근데 울앰 가스라이팅 장인 같아  느그랑 가스라이팅 먹힐 성격같긔  인간들 혐오스러워 가스라이팅 오지고  언냐들 한남 가스라이팅 도와주시긔  정냐는 가스라이팅 하고싶어도 이미 병 든 장혜인 상태라  찐따한남 특 착하고 친절한 봊한테 가스라이팅 존나 함  한남 가스라이팅시키니까기분딱좋노  짭멘갑 같은 새끼들한테 은근슬적 가스라이팅 얹어줘야함  원넨 참치 특징 애미가 가스라이팅 잘시킴  솔직히 한남조심하는건 가스라이팅아니긔  가스라이팅해봤자 한녀들은 토모토모보고 있는데  식민지남성들 주제에 가스라이팅하는거 추하긔  봊들이 혐혼안한다하면 가스라이팅 해대는거 씹  살자 말리는 년들 대부분 김치국이 가스라이팅시킨거라  멘탈 라 한남들 사귈때 가스라이팅으로 살자마려웠는데  띠니 가스라이팅 당했나봄  앰버온냐 대단한게 조니뎁 상대로 가스라이팅함  머두링 가스라이팅당한게 국장 탈퇴감은 아니긴 함  발삼이는 키안커서 가스라이팅에 최적화 되어있긔  트페미들은 왜이리 가스라이팅이라는 단어를 좋아함  가스라이팅때문에 푸르랑 쏘가 욕먹는줄 아는애들이  윾나 진짜로 미동이한테 가스라이팅 당하는중  황발삼 가스라이팅해서 집착하게 만들고 싶긔  딱이가 종삽이 음악적 가스라이팅 함  민주당 저렇게 플랜카드 거는거 가스라이팅 아니노  김치인 종특이 가스라이팅 잘하는거같오  각슬이 이모한테 가스라이팅 당한거 같아  토마토는 가스라이팅 당한거 맞음 그 돼지새끼  잦동생있으면 가스라이팅로 세뇌 존나 시켜야돼  옐무 이거 코디가 가스라이팅한거같긔  덕혜옹주 가스라이팅당한것같음  마토 가스라이팅  토마토 가스라이팅 당했냐  숙달이 걍 주변배슬아재들한테 가스라이팅당해서  헬트한남들 가스라이팅 존나해대면서 피티 연장하라고  흙수저앰앱은 자식 가스라이팅도 많이함  가스라이팅 필터링 뿡라이팅으로 변경합니다  기타갑 주변인들 질투심때문에 존나 가스라이팅했을듯  근데 가스라이팅이란말도 웃기지 않긔  악플러라고 왜패옛날에 띤갤에서 가스라이팅 당한건데  이제 나쁜짓 하다 걸리면 심신미약대신 가스라이팅 타령할듯  앞으론 살인자옆에서 동조하고도 가스라이팅 당했다고 하면될듯  떠려니는 가스라이팅이 아니라 그냥 국장한테 붙어먹는 꼬봉이지  가스라이팅 당했다고 떠려니 또다른 피해자로 만드는거 정말 재밌어  담배갑 탈미는 국장 가스라이팅 안당했는데  띠니는 살때 찐따년 가스라이팅했긔  설현은 가스라이팅에 최적화된 스타일이네  페미 공부 하면서 가스라이팅이 뭔지도 알텐데  떠려니가 가스라이팅 당했다는게 웃긴 이유  근데 떠려니도 국장 가스라이팅에 좀 당한것같은데  찐오아 가스라이팅 당했다 하는 시녀들 나가죽어그냥   국쟝님 이번 일이 화나는건 갈굼 손찌검 가스라이팅 다 있어서가 아닐까  가스라이팅 하다가 도망간 봊친앞에서 칼들고 협박하는 한남  국장 그냥 전형적인 가스라이팅 하는 사람중 하나인듯  국장년 역가스라이팅 하고싶다   가스라이팅했노  뭘 가스라이팅이야  저게 진짜 가스라이팅 아니냐  가스라이팅이 저래서 무서운거긔  머두링 이미 가스라이팅 라 더 안타까워보이는거  떠려니가 가스라이팅 당했다노 시녀들 돌았나봐  우리 앰이랑 언니년이 저런 가스라이팅 잘하긔  머두링 글 보니깐 저 사람들 직접 찾아와서 가스라이팅 존나 했네  칼들고 난리친거 진짜 데이트폭력 가스라이팅 한남 그자체  국장 가스라이팅 관련해서 뭐 참고하는 수준이노  가스라이팅 당해본 온냐있노  멤버가 모를수가없긔 같이 가스라이팅당했든 방관했든  가스라이팅하는애들은 지좋아하는애한테는  한남들끼리 가스라이팅 존나 많아  후햄이 믂가한테 가스라이팅 하는방법 가르쳐줄것같긔  떠려니 절친이면 그냥 닥치지 국장한테 가스라이팅  국장처럼 문재앙 가스라이팅 하고싶어  가스라이팅 기세도 당할 수 있음  국장이 떠려니도 존나 가스라이팅했긔  가스라이팅은 똑똑한봊도 많이당함  가스라이팅 당하면 자존감 바닥찍기  년동안 가스라이팅이면 사람 바뀔수준임  근데 가스라이팅이 로 무섭긴 하노  저렇게 가스라이팅하는놈들 습관이라  성격 순한 언냐들 가스라이팅 당하면 저렇게되긔  가스라이팅 개념이 대중화안돼서 잘모르는듯  그알에 가스라이팅 나올때마다 저런거 왜당하노 햇는데  가스라이팅이 얼마나 위험한건지 실감나긔  년동안 가스라이팅 존나 당했네  본인 착하다고 생각하지 않는데 초딩 때 가스라이팅 오지게 당하고  가스라이팅 주변 사람들이 뭘 어떻게 할 수 있는게 아니긔  숄 머두링 친한거 서로 가스라이팅 안하고  머두링이 세일즈 하는포인트를 국장은 가스라이팅 한거임  두달간 가스라이팅 당할때도 제정신 아니었는데  머두링 가스라이팅 존나 당한건 맞는듯  뿡 근데 회사한테 철저한 가스라이팅 받았나봐  앱 죽었을때가 살이래 연생때부터 가스라이팅 당했을텐데  남앱 뒤져서 울땐 분위기 흐리지말라고 가스라이팅 해놓고  국장이 가스라이팅 존나한듯  여니도 편입전에 가스라이팅 당해봐서 알긔  무서워했으니까 가스라이팅당해서 그렇단년들 존나좌좀마인드같애  국장 답답하다고 하는데 오랫동안 가스라이팅 당하면  머두링 그냥 이것만 봐도 가스라이팅 존나 당한거야  가스라이팅 소설  저런게 가스라이팅이구나  그 어린나이에 가스라이팅 존나 당했네  가스라이팅 그 자체노  한남 가스라이팅 잘함 음침해서 뒤통수침  솔로로 성공해야 가스라이팅 안당함  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  뿡도 가스라이팅 끝났겠노  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  깨박이 현 상태가 실검오르던 가스라이팅아니냐  억지로 묶어두려고 가스라이팅 존나 하겠지  보미는 전형적으로 김봉준한테 가스라이팅 당하고 사네   봉준이 가스라이팅의 교과서 보여주고잇네  김봉준이 채보미한테 하는짓들 다 가스라이팅임  믹테염불은 가스라이팅 당해서 소심해진거 아니노  뚱땡이는 무조건 명이 같이해야된다는 가스라이팅 작작하시긔   가스라이팅   쭈한테 가스라이팅 씹오졌노  믂도 뿡셕한테 가스라이팅 많이 당했나봐  꼴지 치열한거나 보라고 제발 가스라이팅 그만 당하고  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  가스라이팅 존나심해 뿡 병신들맞긔  지코 저새기 또 차돈 가스라이팅하네  개윤기 뿡힛한테 쳐맞고 가스라이팅 당해서 그만나댔으면  뿡힛은 직원들한테도 가스라이팅하나보긔  타요 가스라이팅 실패  믂 이번에 쳐맞고 뿡힛한테 가스라이팅 당해서  푸르때매 가스라이팅 의미 제대로 알고 간다  푸르는 공혁준한테 당한게 있어서 가스라이팅 피했네  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  근데 뿡 가스라이팅 당한거 보이지 않긔  피해자한테 가해자 왜 믿었냐고 가스라이팅 하는 곡 썼노  일어나지 않은 일로 가스라이팅 그만하고  뿡 나가면 명 다 좆된다고 가스라이팅하노  그냥 가스라이팅 당한 병신들임   믹테 꼬우면 작곡하라는말이 가스라이팅이 아니면 뭐야  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  띠니 가스라이팅 당해서 라도처럼만 안나오면 포용이기  뿡힛가스라이팅 년이면  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡은 미성년자때부터 뿡셕한테 가스라이팅 당해서  갓성은 저게 진짜 그루밍 가스라이팅 아님  뿡픽애미들 가스라이팅 노무 싫긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  뿡힛좆같은 가스라이팅 그만해  호남향우회 모르냐 라도가 뿡 가스라이팅하면서 조정해  납견이지만 지코가 푸린잉한테 하는짓은 가스라이팅임   뿡은 뿡힛가스라이팅땜에 자발적노예야  쭈 옆에서 후려치고 계속 가스라이팅하다보면  니들도 가스라이팅 조심해라   헐 맞아 가스라이팅 대표적인게 네가 예민한거야  가스라이팅이란 단어 많이 씀  뿡 가스라이팅으로 빡대갈들맞지만  뿡힛가스라이팅 지금도하잖아  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  황래혁이 여친한테 하는게 전형적인 가스라이팅임   관리하에 가스라이팅 당하고 지배당햇던거지   뿡은 뿡셕한테 가스라이팅 당한거라니까  난 뿡이 뿡힛에 가스라이팅 당한거라고도 생각했긔  알수록 뿡힛은 을위치 연생들 가스라이팅 시켜서  갤사세로 좆치질 가스라이팅하는거 신경쓰지마시긔  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  보단 낫다는게 가스라이팅이지  뿡셕이 젤 가스라이팅도 잘하고 뿡차별 젤 심해  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  막내 꾹이 분량 몰빵은 당연한걸로 가스라이팅 당함  뿡도 가스라이팅 끝났겠노  뿡 돈계산 철저하게 하면 욕심이라고 가스라이팅이라도  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  기생하려고 올뿡 가스라이팅질  억지로 묶어두려고 가스라이팅 존나 하겠지  믹테염불은 가스라이팅 당해서 소심해진거 아니노  올뿡이 왜 필요하노 뿡힛 뿡한테 가스라이팅 당하노  뿡힛에 가스라이팅 당한게 아니라 아미녀들이 지랄하는데  뿡이 가스라이팅당해서 뿡힛 나올 생각이 없으면  뿡셕 가스라이팅 심한건 다 느껴지지 않음  믂도 뿡셕한테 가스라이팅 많이 당했나봐  뿡 착한것도 가스라이팅된거니  이게 다 뿡이 가스라이팅 당한 탓이긔  라도 착하다는것도 다가스라이팅이야  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  갠활 시작하면 가스라이팅 소용없어  가스라이팅 존나심해 뿡 병신들맞긔  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  뿡힛 뿡셕 뿡 가스라이팅 존나 싸패같긔  시발 가스라이팅이 이렇게 무섭노 쭈가무능력이면  뿡힛가스라이팅 더이상 못참아  뿡 나가면 명 다 좆된다고 가스라이팅하노  가스라이팅 진짜 너무 심해  아무튼 다 가스라이팅 당해서 곡 뭐라도 써내는데  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  저번에 뿡 가스라이팅하던 직원이 이번에도 믂 꼽준거 맞긔  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡힛이랑 라도가 뿡 가스라이팅하는거 같아서  찜 뿡힛에 가스라이팅당해서 그렇긔  뿡픽애미들 가스라이팅 노무 싫긔  갑분 가스라이팅 장면 나오긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  쭈 옆에서 후려치고 계속 가스라이팅하다보면  헐 맞아 가스라이팅 대표적인게 네가 예민한거야  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  딘딘팸 나이차 많이나서 가스라이팅 오짐  분량 가스라이팅이라보 패니까 아무거나 가스라이팅이노  라도가 뿡빠기단 가스라이팅 오져 호남향우회의 전형적인  빅히트 뷔 가스라이팅 발버둥 처절하다  뿡셕 돼지새끼 이러고도 꾹 올려치기하고 찜 가스라이팅해봐  뿡셕 이새끼 보컬라인 가스라이팅 하는거 놈 티나  디패 번 터졌으면 가스라이팅 당한거지  약지슥 가스라이팅 당한다  윾정이 가스라이팅 안당하고 그 웃음 잃지 말길  근데 회사원들은 가스라이팅해야 좀 말잘듣긴하긔  근데 뿡 가스라이팅 너무 오래당해서 금방 소송 접을듯  득저씨 미친놈들이 가스라이팅해서 빻은 대표님  득저씨들 머효욕은 왜하노 가스라이팅 했으면서  역시 가스라이팅 전문 소속사 답노  숄 가스라이팅 당했을듯  숄가스라이팅 당한거긔  나 가스라이팅 존나 당하고 살았긔  띠니 어린잦 가스라이팅해서 따먹고 차였긔  숄은 누가봐도 개저씨한테 가스라이팅 당하면서  최자법 청원해주시긔 늙은한남 가스라이팅 처벌법  지가한남이니까 가스라이팅쓰면 왕따당하겠지  가스라이팅이란 단어 쓰면서 진지빨지는 마시긔  한남들이 가스라이팅에 발작하는거보니 이단어는 쓰는게맞긔  가스라이팅은 한녀로 태어났으면 무조건 당하는건데  가스라이팅이 왜 오글거린다는거긔  페미유행되기 전까지 한남한테 가스라이팅 안당해본 봊이  책안읽는데 책 많이사는거 가스라이팅이긔  노무현 사망 이런게 가스라이팅이긔  가스라이팅 잘하는 사람들은 그냥 열등감 심한거만 보면돼  가스라이팅 단어 드라마에도 나와  가스라이팅 쓰는애들 큰일나  근데 왜 가스라이팅이야  가스라이팅에 발작하는거 한남 맞네  가스라이팅 그런단어 쓰는애들 정신이상자들  가스라이팅 교양수업에나오는데  가스라이팅이 교양수업에 나왓대   가스라이팅 용어랑 상관없이 한남이 봊 후려치는거  영어단어 잘만 쓰면서 가스라이팅만 오글거리노  가스라이팅 오글거린다는 것도 가스라이팅임  아니근데 가스라이팅이란말 봊학식들 존나쓰는데  가스라이팅 싫으면 후려치기라고 해  가스라이팅 안당하려면 주위에 자랑같은거 하지마  가스라이팅을 일상에서 못쓴다는건 얼마나  쇼타 한명 가스라이팅해서 그루밍하고 싶긔  가스라이팅 오글거리는거랑 별개로 퍼지는게 봊한테 좋은건데  가스라이팅 같은게 퍼져야 최자같은 한남이 사리고다님  다른겅 몰라도 가스라이팅 맨스플레린 인플래이션이 오글거린단  가스라이팅은 성장기에 친구들한테 제일 많이 당하는것같음  맞노 빻순이짓 할때 가스라이팅 당했긔  김치국은 오지랖 라 가스라이팅이 일상이잖아  안토가 예섹 가스라이팅 해서 사겻으면 좋겟다  가스라이팅 노력한다고 안당하는거 아님  가스라이팅 아예 안당하는 사람 없음  누가 가스라이팅 시도하려고 할 때 참고하시긔  맞긔 가스라이팅 벗어나는법은 주관이 뚜렷하고  가스라이팅 어감이 너무 별로야  가스라이팅이고뭐고 그냥 만나고올때마다 기분찝찝하면 손절하는게 맞는듯  가스라이팅이라는 말 알려져서 좋은데  가스라이팅이 근본도없댄다  가스라이팅이라는 단어 혼모노같다는거   연예인들이 대부분 가스라이팅 잘당하는 그런유형의 사람들이 많음  빻은봊이 이쁜봊 가스라이팅하는것만큼 추한게 없긔  친구가 가스라이팅그게 친구노  가스라이팅 하는 새끼들 열에 아홉이  가스라이팅 잘당하는 피해자공통점이  가스라이팅 잘 당하는 사람들 특징이 뭐임  그얼굴로 가스라이팅 당한 숄 불쌍해  저 마귀할멈으로부터 윙족이 지키시긔 가스라이팅 당할라  망수 나가기 직전에 숄 보면 진짜 그 상폐남이 어떻게 가스라이팅을 했길래  잦만날때 가스라이팅 당하면 망가지긔  가스라이팅이 무슨 뜻이기  숄은 이쁜게문제가아니라 외모때문에 가스라이팅당하고  인지왜곡 시키는것 가스라이팅이긔  온냐들 잦중억 가스라이팅 하면서 호감표하는 잦알긔  읍나빛최잦 가스라이팅에 숄 좆예인인거  가스라이팅 당해서 정병심해진듯  띠니 급식때 가스라이팅당해서 씹찐따처럼 하고다녀서 찐따됐었는데  가스라이팅 썰 풀어보길래 쓴거야  약뱅노래 좋다는년들 읍죄기성적 언플에 가스라이팅 당한거야  종교는 애초부터 지배층이 가스라이팅 하는 용도였는데  가스라이팅이 모야  모성애 올려치는것도 가스라이팅임  텅텅뮤 가스라이팅 그만하시긔  김수미 할매한테 가스라이팅 당하는 대잦 내용 보고싶어  한남문학 종특은 봊 가스라이팅 안하면 연애 못함  뿡 근데 다들 가스라이팅 당하고 정병라 잘 꼬시면 띠니도 사귈수있을듯  남의식 약간 은따나 가스라이팅 많이 당하면 그렇게됨  언냐들 가스라이팅 조심해   휴메띠니 가스라이팅 하고싶긔  결혼하고 독박살림에 가스라이팅 존나 당한거면  저거도 구줌이 필터링한거 같긔 더 심한 말도 하면서 가스라이팅했노  구혜선 가스라이팅한 한국남자 면상  한녀들 와꾸 지나치게 안 보는 것도 가스라이팅 당한것 같아  년동안 남동충 가스라이팅시켜서 집안일떠맡겼긔  갓파 살때부터 납치해서 가스라이팅 존나 한다음에  흰수만 꾸니 트름랩에 가스라이팅 당하고 있나봐  가스라이팅 당하는 의뚝이  스스로 가스라이팅 미쳤노  뿡은 맨날 가스라이팅 하니까 허허충에 발작하는거긔  윽신이 봊친한테 가스라이팅 잘할거같음  일단 한남들이 만든 영화 모든게 다 봊들 가스라이팅시키고 기죽일려고  왜 좁이 주위엔 좁이 가스라이팅해줄 사람이 없을까  뿡 행복충아니긔 요새 가스라이팅당하고 불행충이었긔  찜 오늘 뮤뱅엔딩 영상으로 가스라이팅 오지게 당하겠노  삐에게 가스라이팅하는 한남 믂  딱쭈는 딱이가 쭈 가스라이팅 시도하다가  좁스부치언니 딱갤주 가스라이팅 성공한듯  김랩괴 가스라이팅 해서라도 갖고만다  딱이 좁이보고 코르셋조이라고 가스라이팅하다가  한녀들 그냥 단체로 정신병왓다니깐 하도 가스라이팅당해서  뿡는 가스라이팅 흙수저타령 명품백타령 안해서 좋긔  하괴윙족문학 가스라이팅  근데 한남한테 가스라이팅 당하면 존나좆같겟다  좁이 누가 가스라이팅 좀 해  혐애미들 존아 명잦이다 가스라이팅 중  짐승한테까지 가스라이팅 당해서 지 재산 쏟아붓는 병신년들  언냐 친구들이 가스라이팅하노  김주영 가스라이팅 최고긔  살면서 가스라이팅하고만 살아올것같은게 꾹인데  뿡은 꾹빼고 한남 가스라이팅 오져  언냐들 가스라이팅에 넘어가지좀 마시긔  서키 맘에드는 젊은 봊 있으면 가스라이팅 오지게했을듯  존나 능글거리면서 대놓고 가스라이팅하는 한남 존나싫어  가스라이팅 대놓고 하는 한남 볼때 존나 빡쳐  씹가위년들 한남 빙의해서 봊한테 가스라이팅 존나 해  띠니 가스라이팅 뜻 이제 알았오  퀸주영 가스라이팅   가스라이팅 하고싶어  가스라이팅 존나당하면 진짜 정신 이상해지는거같애  새내기시발련 가스라이팅 존나해서 좆생 망가뜨릴거야  가스라이팅이라는 단어랑 뿌주부랑 같은 문장에 잇는게 왤케 웃기지  뿌주부 가스라이팅 기술 라고 느꼇던거  가스라이팅깅  씹댕청한 잘생긴 잦 예쁜 봊 가스라이팅깅 하고싶기  가스라이팅이 뭐긔  띤갤언냐들 가스라이팅해서 띠니 시녀로 만들고싶긔  변요한띠니도 가스라이팅 당함  가스라이팅도 사랑인데 노무 왜곡하지는 마시긔  띠니는 가스라이팅과 사랑을 동일시하게 생각하긔  좆간대할때 이런생각 한번이라도 햇으면 가스라이팅 당한거야  가스라이팅 왕진진이 낸시랭한테도하던데  직장상사가 가스라이팅하는데 칼빵찌르고싶었긔  으누가 가스라이팅해주면 좋겠다 헌법으로 만들어야됨  가스라이팅 당하는년들 솔직히 지들도 알고잇긔  자기얘기만 안 해도 거의 가스라이팅 당할일 없긔  가스라이팅 당하는년들 특 분명 잘못해서 화냇는데 불안함  가스라이팅 유래 이거긔  가스라이팅 당사자말고 가해자일땐 진짜 존나재밋어  인싸새내기들 머갈통 쳐빻아서 가스라이팅해도 몰라  인싸새내기 씹입생들 가스라이팅 맨스플레인 하고싶긔  진짜 봊이면 대쉬 못받는다는것도 한남들 가스라이팅이긔  와꾸아니라도 빨거있는 새끼는 가스라이팅을 존나 해야됨  딱갤주가 좁깅이 머리로 후려치고 가스라이팅하는거 보고싶긔  제발 딱이가 좁이 옆에두고 가스라이팅 존나 했으면  똥미노 부랄에다 기름붓고 가스라이팅하고싶긔노윤딱  김경수 가스라이팅 존나 잘하게 생김  난 오히려 윰멍이 자기도 가스라이팅 피해자고  생각해보니까 윰댕도 김이브한테 가스라이팅당해서 몇년동안 끌려다녔잖아  좁이는 왜 가스라이팅도 안당하노  좁이 머리자르지말라는게 왜가스라이팅이긔  부니 머리로 가스라이팅 좀 당해야돼  머큐리 게이매니저가 가스라이팅 한거같은데  가스라이팅으로 흙수저 컨셉 잡아놓고 돈버니까 명품휘두르고다님  좁이 누가 가스라이팅 좀 하라고  앙준이 댕청해서 가스라이팅하고싶자나  트페미들아 니네 좌빨한테 가스라이팅 당한건 암  트페미들이 하는게 가스라이팅이긔  양아치 폰팔이 훈남한테 가스라이팅 당해서 동거하고 싶다  양남은 잦으로 안 보인다는것도 가스라이팅 당한거긔  한남친구한테 가스라이팅했는데  개독 가스라이팅인생 최후의 행복회로  봉랑이 가스라이팅 존나 잘할거같음  갓파 가스라이팅하기 최적화 아니긔  앙준이 가스라이팅 하면서 사귀고 싶어   한남들 가스라이팅해서 꼬무룩하게 만드는 법은   연하남 가스라이팅하면서 만나고싶긔  이오빠한테 가스라이팅 당하고싶다  근데 왜 한남새끼들은 와꾸도 고추도 좆빻은게 가스라이팅이 일상화되있음  가스라이팅하는방법  가스라이팅이고 지랄이고 작작싸워 미친년들아  트페미 시발년들 가스라이팅 뜻은 제대로 알고 말하는거노  내가 실제로봤던 가스라이팅 하나밖에없음  가스라이팅 좆돌새끼들한테 하면   가스라이팅 설명하는 년이 설명을 잘못했네  가스라이팅으로 한남패니까 이지랄난거잖아  가스라이팅플도 그냥 한마음으로 한남 패면 되는데  가스라이팅이 뭔데 가스에 불붙듯 서서히 유혹하는거임  가스라이팅이 걍 후려친다기 보다는 닌 나없으면  가스라이팅이라는건 정말 멍청하면 못하는짓인건 맞음  의견다른걸 억지로 세뇌시키는게 가스라이팅이라며  가스라이팅 영어단어있다니까 이거 이야 트페미용어아님  왜또 가스라이팅갤이냐 이기야  가스라이팅 얘기한지 얼마나됐다고 발작하는 이유가 뭐긔  트페미 시발년들아 니네가 가스라이팅 트리거를  서창빈 가스라이팅 해서 은퇴시키고 싶다  가스라이팅 좌좀들이잘함  가스라이팅 당했네 이러는거 솔직히 폭토커가 지 싸패라 그러는거 보는 기분  새끼 가스라이팅하고싶다  가스라이팅이라는 단어에 발작하는 이유  나 좆이콘한테 가스라이팅 당햇긔  가스라이팅은 후려치기랑은 조금 다른느낌  맨날 앰한테 가스라이팅당하는데 자존감 안떨어짐  김치국에서 가스라이팅 안 당하는 봊이 없을텐데  가스라이팅 이지랄하는거 존나 트페미같다  가스라이팅말고 동숲갤하자  가스라이팅인가 그딴거 미자때 아님 당하는거 존나 이해안됨  가스라이팅말고 다른말없노 존나 트페미같아  왜 갑자기 가스라이팅 갤이긔  가스라이팅이 뭔데  전라도 남자들이 가스라이팅을 잘함  가스라이팅이 존나 무서운게 봊이 뒤질때까지 쳐맞고도  글고 가스라이팅이 진짜 무서운게 어떻게 그 무리에서  잦친한테 가스라이팅 당하는 봊도 진짜 이상한게  우리나라 전체가 봊상대로 가스라이팅 한다는거 맞음  가스라이팅하는 한남들 강약약강임  가스라이팅 걸릴 새끼만 걸린단건 뻘소리긔  가스라이팅 방법중에 하나 이거라하긩  존나 가까운 사람이 가스라이팅 했다고 생각해봐  가스라이팅 저거 어원도 만 걸려드는거 맞네  가스라이팅이 머임 나도 할래  존나긴반고닉이 나한테 자꾸 시비거는것도 가스라이팅이긔  호모문학에 트리거 가스라이팅 이러는거 존나같잖아  가스라이팅 우리애미가 존나잘해  가스라이팅 어원 존나 소름돋긔  가스라이팅도 당해본 사람이 잘함  가스라이팅 동등한관계보다 수직관계에서 잘먹힐듯  가스라이팅이 페미용어래도 저정도는 인식하고 있어야하긔  가스라이팅에서 벗어나는건 쉬울거같음  가스라이팅 자존감낮은 머리좋은애들이잘함  가스라이팅 트페미용어 맞음  가스라이팅 존나 잘하는 년들이 있긔  저 태국똥냐옵 구해줘야 되는 거 아님 가스라이팅 당하는 중인 것 같아  시녀들 지가빠는 봊돌 라고 가스라이팅 시동거는거 토나와  보다보면 잘생겼다 이거 착즙이나 가스라이팅 둘 중하나임  마시도 그렇고 안토도 그렇고 나는 꾸며도 안된다고 가스라이팅 된 봊들 불쌍해  으누가 가스라이팅 하는건 그냥 사랑이지  은우한테 가스라이팅 당하고 싶어  으누한테는 가스라이팅 당하고 싶어  난 은오후 가스라이팅 하고싶긔  앙준이 가스라이팅하고싶어  가스라이팅 호모웹툰없노  방탄 아미한테 가스라이팅 오지게 하네  며느리에게 가하는 가스라이팅  가스라이팅 예시 아는 사람  친구년 하는 짓 가스라이팅 맞지  나 가스라이팅 해봐  이것도 가스라이팅이라고 할   가스라이팅 당하는 거 같아요  상식 가스라이팅에 대해서 알아보자 똑똑한 병신들만 클릭 
"""

In [248]:
t = Tokenizer()
t.fit_on_texts([text1])
vocab_size = len(t.word_index) + 1
# 케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야하므로 미리 +1 선언 
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 1581


In [249]:
t.word_index

{'가스라이팅': 1,
 '존나': 2,
 '가스라이팅이': 3,
 '뿡': 4,
 '한남': 5,
 '근데': 6,
 '가스라이팅으로': 7,
 '당한거야': 8,
 '뿡이': 9,
 '그냥': 10,
 '당해서': 11,
 '진짜': 12,
 '가스라이팅당해서': 13,
 '당하고': 14,
 '년간': 15,
 '막내푸쉬': 16,
 '뿡은': 17,
 '가스라이팅해서': 18,
 '하는': 19,
 '당하는': 20,
 '가스라이팅에': 21,
 '다': 22,
 '왜': 23,
 '당한': 24,
 '가스라이팅은': 25,
 '좀': 26,
 '단어': 27,
 '가스라이팅이라는': 28,
 '뿡힛': 29,
 '나': 30,
 '많이': 31,
 '언냐들': 32,
 '띠니': 33,
 '머두링': 34,
 '국장': 35,
 '그': 36,
 '당하면': 37,
 '뿡셕': 38,
 '당한거긔': 39,
 '가스라이팅이긔': 40,
 '좁이': 41,
 '당함': 42,
 '오지게': 43,
 '봊': 44,
 '당한거': 45,
 '누가': 46,
 '한남들': 47,
 '노무': 48,
 '가스라이팅도': 49,
 '숄': 50,
 '뿡셕이': 51,
 '케어': 52,
 '가스라이팅임': 53,
 '년동안': 54,
 '가스라이팅하는': 55,
 '저': 56,
 '한남한테': 57,
 '봊이': 58,
 '아니노': 59,
 '그만해': 60,
 '같아': 61,
 '가스라이팅하는거': 62,
 '맞음': 63,
 '걍': 64,
 '하면서': 65,
 '케어로': 66,
 '뿡셕한테': 67,
 '젤': 68,
 '아님': 69,
 '가스라이팅을': 70,
 '안': 71,
 '있는데': 72,
 '불쌍해': 73,
 '거': 74,
 '자존감': 75,
 '놈': 76,
 '나한테': 77,
 '없긔': 78,
 '아니긔': 79,
 '한남이': 80,
 '가스라이팅하면서': 81,
 '라고': 82,
 '하고싶어': 83,
 '빅히트가

In [250]:
text3 = list()
for line in text1.split('  '):
    text3.append(line)

In [251]:
sequences = list()

for line in text3: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

sequences[:11] # 11개의 샘플 출력
len(sequences)

2076

In [252]:
print(sequences)

[[291, 292], [291, 292, 18], [291, 292, 18, 293], [291, 292, 18, 293, 294], [295, 296], [295, 296, 297], [295, 296, 297, 298], [295, 296, 297, 298, 299], [295, 296, 297, 298, 299, 1], [295, 296, 297, 298, 299, 1, 42], [300, 119], [300, 119, 72], [300, 119, 72, 120], [300, 119, 72, 120, 1], [300, 119, 72, 120, 1, 301], [300, 119, 72, 120, 1, 301, 302], [121, 122], [121, 122, 303], [121, 122, 303, 304], [121, 122, 303, 304, 305], [121, 122, 303, 304, 305, 306], [307, 308], [307, 308, 309], [307, 308, 309, 310], [311, 1], [311, 1, 24], [311, 1, 24, 312], [311, 1, 24, 312, 73], [313, 314], [313, 314, 1], [313, 314, 1, 315], [313, 314, 1, 315, 2], [313, 314, 1, 315, 2, 316], [317, 318], [317, 318, 319], [123, 1], [123, 1, 24], [123, 1, 24, 74], [123, 1, 24, 74, 124], [320, 10], [320, 10, 321], [320, 10, 321, 322], [323, 1], [323, 1, 1], [323, 1, 1, 324], [323, 1, 1, 324, 325], [323, 1, 1, 324, 325, 326], [323, 1, 1, 324, 325, 326, 327], [328, 329], [328, 329, 54], [328, 329, 54, 330], [328,

In [253]:
max_len=max(len(l) for l in sequences)
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [254]:
sequences

array([[   0,    0,    0, ...,    0,  291,  292],
       [   0,    0,    0, ...,  291,  292,   18],
       [   0,    0,    0, ...,  292,   18,  293],
       ...,
       [   0,    0,    0, ..., 1576, 1577, 1578],
       [   0,    0,    0, ..., 1577, 1578, 1579],
       [   0,    0,    0, ..., 1578, 1579, 1580]])

In [255]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [256]:
y = to_categorical(y, num_classes=vocab_size)

In [257]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [94]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [258]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, verbose=2)

Epoch 1/150
65/65 - 1s - loss: 7.2131 - accuracy: 0.1190
Epoch 2/150
65/65 - 1s - loss: 6.6876 - accuracy: 0.1209
Epoch 3/150
65/65 - 1s - loss: 6.5774 - accuracy: 0.1209
Epoch 4/150
65/65 - 1s - loss: 6.5155 - accuracy: 0.1209
Epoch 5/150
65/65 - 1s - loss: 6.4482 - accuracy: 0.1209
Epoch 6/150
65/65 - 1s - loss: 6.3862 - accuracy: 0.1209
Epoch 7/150
65/65 - 1s - loss: 6.3297 - accuracy: 0.1209
Epoch 8/150
65/65 - 1s - loss: 6.2693 - accuracy: 0.1209
Epoch 9/150
65/65 - 1s - loss: 6.1901 - accuracy: 0.1214
Epoch 10/150
65/65 - 1s - loss: 6.0768 - accuracy: 0.1243
Epoch 11/150
65/65 - 1s - loss: 5.9284 - accuracy: 0.1301
Epoch 12/150
65/65 - 1s - loss: 5.7649 - accuracy: 0.1315
Epoch 13/150
65/65 - 1s - loss: 5.5938 - accuracy: 0.1315
Epoch 14/150
65/65 - 1s - loss: 5.4360 - accuracy: 0.1334
Epoch 15/150
65/65 - 1s - loss: 5.2752 - accuracy: 0.1305
Epoch 16/150
65/65 - 1s - loss: 5.1325 - accuracy: 0.1387
Epoch 17/150
65/65 - 1s - loss: 4.9991 - accuracy: 0.1397
Epoch 18/150
65/65 - 1s

Epoch 142/150
65/65 - 1s - loss: 0.9293 - accuracy: 0.7789
Epoch 143/150
65/65 - 1s - loss: 0.9218 - accuracy: 0.7890
Epoch 144/150
65/65 - 1s - loss: 0.9147 - accuracy: 0.7929
Epoch 145/150
65/65 - 1s - loss: 0.8999 - accuracy: 0.7924
Epoch 146/150
65/65 - 1s - loss: 0.8906 - accuracy: 0.7895
Epoch 147/150
65/65 - 1s - loss: 0.8815 - accuracy: 0.7996
Epoch 148/150
65/65 - 1s - loss: 0.8728 - accuracy: 0.8011
Epoch 149/150
65/65 - 1s - loss: 0.8689 - accuracy: 0.8006
Epoch 150/150
65/65 - 1s - loss: 0.8624 - accuracy: 0.7987


In [259]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=10, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [263]:
print(sentence_generation(model, t, '가스라이팅', 4))

가스라이팅 안당하면 어쩌란거긔 친구도 아니고


In [76]:
print(sentence_generation(model, t, '감봉크루', 3))

감봉크루 감크루 봉퀴 감봉크루라고안한다


In [80]:
print(sentence_generation(model, t, '감봉크루는', 10))

감봉크루는 맞는데 그럼 비글즈 인방갤 에프킬라 감봉크루 감크루 봉퀴 감봉크루라고안한다 감크루감컴퍼니지


In [81]:
print(sentence_generation(model, t, '감봉크루가', 10))

감봉크루가 맞는데 그럼 비글즈 감크루 감크루 봉퀴 감봉크루라고안한다 감크루감컴퍼니지 철감 통일합니다


In [82]:
print(sentence_generation(model, t, '감봉크루에', 10))

감봉크루에 맞는데 김봉준이 승자는 등장해 한다고 비글즈따위 안됨 안됨 아니지 아니지


In [105]:
encoded = t.texts_to_sequences(['가스라이팅'])[0] # 현재 단어에 대한 정수 인코딩
encoded

[1]

In [106]:
encoded = t.texts_to_sequences(['가스라이팅'])[0] # 현재 단어에 대한 정수 인코딩
encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
result = model.predict_classes(encoded, verbose=0)

In [107]:
result

array([638], dtype=int64)

In [ ]:
# 앞에것 잘라서 가져오기

In [264]:
text1 = """
잦동충은 유충때부터 가스라이팅해서 기 눌러놔야됨  잦동충 있는년들 띵잦이 많긔 앰앱한테 가스라이팅 당함  잦동생 한명 있는데 어릴때부터 가스라이팅 시켰더니 긔  잘생긴 잦 묶어놓고 존나패고 가스라이팅하고싶으면 이상성욕이긔  나래코기랑 도연언냐는 나래코기가 가스라이팅한거긔  몇백년동안 가스라이팅 당한 한녀 불쌍해  머학 새내기때 가스라이팅 당하기 존나 쉬워   전래동화라면서 좆기때부터 가스라이팅시키노  토마토 가스라이팅 당한 거 맞지  봊초년들특징이 그냥 팩트말하면 가스라이팅이라함  와 가스라이팅 가스라이팅 말만 듣고 뜻만 알았지  족구 군대간 년동안 가축들이 가스라이팅 당함  봉준이방송은 가스라이팅방송임  지금 케이는 가스라이팅 중임  딱 여자들이 좋아하는 단어 가스라이팅 오지게 당한거지 푸르는  최군은 가스라이팅 잘하지  사실 방송 별거 아닌데 혜디주변에서 혜디 가스라이팅하는게 참  어릴때부터 가스라이팅 당해서 자존감 하나도 없어  개딱단과 개엑이야 말로 가스라이팅 한거긔  김극라는 가스라이팅하는 봊 만나야해  혹시 공주 가스라이팅 당한거 아닐까윤  저 말한 놈 그단톡방에서 가스라이팅 당한거같긔  여니 잇팁인데 가스라이팅이라는 단어 이해안됨  뿡힛 가스라이팅이 믹테야 적어도 보컬한테는  씹매들시대엔 봊기때부터 가스라이팅해서 살때  중딩때 나한테 오지게 가스라이팅한년 죽이고싶어  빻다빠는년들 가스라이팅 잘당할것같긔  현실에서 가스라이팅 병신끼리 주고받지 않노  가스라이팅 당하고살긔  하 시발 가스라이팅 인 새끼 있는데  나 가스라이팅 존나 당함  누가 나 가스라이팅 시도한적 없긔  는 가스라이팅 절대 안당함  가스라이팅 문장 저거 한남들 단골멘트 아니긔  한남한테 가스라이팅하면 한남이 나한테 의지해서  한남한테 가스라이팅해보고싶노  띠닌 인데 가스라이팅 이해가긔  가스라이팅 이해 안가는 언냐  잇팁 가스라이팅 이해 안간다는거 딱 한남같노   인데 가스라이팅 당하는거 존나 이해안가긔  발삼이 잦스틴이 가스라이팅 시켜놨으니까 놔줘  한남 좃 웃긴거 누가 널 만나주냐는 식으로 가스라이팅하면서  한녀들은 한남 존나싫다는데 왤케 가스라이팅하는거노  라도춤은 뿡힛식 강제 가스라이팅이지 라도춤이 어디서  망망프다이어리 녕동민 가스라이팅 너무당해서  스시잦들 투잡가스라이팅대리효도없는것만으로도 라고 생각했었는데  한녀들이 당한 역대급 가스라이팅은 반일선동이라고 생각해  황발삼 가스라이팅 하고싶어  빅히트가 개인방 몇명만 준거 가스라이팅 이긔  의새도 환자 가스라이팅 하는 의새 개많아  미동이가 윾나 가스라이팅하려는거같애서 놈 혐오스럽긔  가스라이팅 단어도 변질됨  잦친한테 자격지심들고 가스라이팅 당한거 생각하면 노무 분해  빻다 옆에서 못생겼다고 가스라이팅 시킬 봊이 필요함  메리는 가스라이팅 안통할 것 같긔  강섹훈 가스라이팅 존나 시키고 싶긔  나 감쓰삼고 가스라이팅하던 틀딱년들 손절했는데  혐애할때 유독 한녀들만 가스라이팅 존나당하는거 같긔  득팔이 노무 못생겼기도 하고 주변에서 가스라이팅 많이 당했을긋  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  진심 성형 보편화 된거 한남 가스라이팅 아니노  봊친한테 휘둘리며 가스라이팅 당하는 딘쿵야  녀살려야 아메한테 가스라이팅 그만해  가스라이팅 당한 봊자식은 사실 제대로 반항도 못해  이런갤열면 앰생한남들 기어들어와서 가스라이팅 시작함  근데 울앰 가스라이팅 장인 같아  느그랑 가스라이팅 먹힐 성격같긔  인간들 혐오스러워 가스라이팅 오지고  언냐들 한남 가스라이팅 도와주시긔  정냐는 가스라이팅 하고싶어도 이미 병 든 장혜인 상태라  찐따한남 특 착하고 친절한 봊한테 가스라이팅 존나 함  한남 가스라이팅시키니까기분딱좋노  짭멘갑 같은 새끼들한테 은근슬적 가스라이팅 얹어줘야함  원넨 참치 특징 애미가 가스라이팅 잘시킴  솔직히 한남조심하는건 가스라이팅아니긔  가스라이팅해봤자 한녀들은 토모토모보고 있는데  식민지남성들 주제에 가스라이팅하는거 추하긔  봊들이 혐혼안한다하면 가스라이팅 해대는거 씹  살자 말리는 년들 대부분 김치국이 가스라이팅시킨거라  멘탈 라 한남들 사귈때 가스라이팅으로 살자마려웠는데  띠니 가스라이팅 당했나봄  앰버온냐 대단한게 조니뎁 상대로 가스라이팅함  머두링 가스라이팅당한게 국장 탈퇴감은 아니긴 함  발삼이는 키안커서 가스라이팅에 최적화 되어있긔  트페미들은 왜이리 가스라이팅이라는 단어를 좋아함  가스라이팅때문에 푸르랑 쏘가 욕먹는줄 아는애들이  윾나 진짜로 미동이한테 가스라이팅 당하는중  황발삼 가스라이팅해서 집착하게 만들고 싶긔  딱이가 종삽이 음악적 가스라이팅 함  민주당 저렇게 플랜카드 거는거 가스라이팅 아니노  김치인 종특이 가스라이팅 잘하는거같오  각슬이 이모한테 가스라이팅 당한거 같아  토마토는 가스라이팅 당한거 맞음 그 돼지새끼  잦동생있으면 가스라이팅로 세뇌 존나 시켜야돼  옐무 이거 코디가 가스라이팅한거같긔  덕혜옹주 가스라이팅당한것같음  마토 가스라이팅  토마토 가스라이팅 당했냐  숙달이 걍 주변배슬아재들한테 가스라이팅당해서  헬트한남들 가스라이팅 존나해대면서 피티 연장하라고  흙수저앰앱은 자식 가스라이팅도 많이함  가스라이팅 필터링 뿡라이팅으로 변경합니다  기타갑 주변인들 질투심때문에 존나 가스라이팅했을듯  근데 가스라이팅이란말도 웃기지 않긔  악플러라고 왜패옛날에 띤갤에서 가스라이팅 당한건데  이제 나쁜짓 하다 걸리면 심신미약대신 가스라이팅 타령할듯  앞으론 살인자옆에서 동조하고도 가스라이팅 당했다고 하면될듯  떠려니는 가스라이팅이 아니라 그냥 국장한테 붙어먹는 꼬봉이지  가스라이팅 당했다고 떠려니 또다른 피해자로 만드는거 정말 재밌어  담배갑 탈미는 국장 가스라이팅 안당했는데  띠니는 살때 찐따년 가스라이팅했긔  설현은 가스라이팅에 최적화된 스타일이네  페미 공부 하면서 가스라이팅이 뭔지도 알텐데  떠려니가 가스라이팅 당했다는게 웃긴 이유  근데 떠려니도 국장 가스라이팅에 좀 당한것같은데  찐오아 가스라이팅 당했다 하는 시녀들 나가죽어그냥   국쟝님 이번 일이 화나는건 갈굼 손찌검 가스라이팅 다 있어서가 아닐까  가스라이팅 하다가 도망간 봊친앞에서 칼들고 협박하는 한남  국장 그냥 전형적인 가스라이팅 하는 사람중 하나인듯  국장년 역가스라이팅 하고싶다   가스라이팅했노  뭘 가스라이팅이야  저게 진짜 가스라이팅 아니냐  가스라이팅이 저래서 무서운거긔  머두링 이미 가스라이팅 라 더 안타까워보이는거  떠려니가 가스라이팅 당했다노 시녀들 돌았나봐  우리 앰이랑 언니년이 저런 가스라이팅 잘하긔  머두링 글 보니깐 저 사람들 직접 찾아와서 가스라이팅 존나 했네  칼들고 난리친거 진짜 데이트폭력 가스라이팅 한남 그자체  국장 가스라이팅 관련해서 뭐 참고하는 수준이노  가스라이팅 당해본 온냐있노  멤버가 모를수가없긔 같이 가스라이팅당했든 방관했든  가스라이팅하는애들은 지좋아하는애한테는  한남들끼리 가스라이팅 존나 많아  후햄이 믂가한테 가스라이팅 하는방법 가르쳐줄것같긔  떠려니 절친이면 그냥 닥치지 국장한테 가스라이팅  국장처럼 문재앙 가스라이팅 하고싶어  가스라이팅 기세도 당할 수 있음  국장이 떠려니도 존나 가스라이팅했긔  가스라이팅은 똑똑한봊도 많이당함  가스라이팅 당하면 자존감 바닥찍기  년동안 가스라이팅이면 사람 바뀔수준임  근데 가스라이팅이 로 무섭긴 하노  저렇게 가스라이팅하는놈들 습관이라  성격 순한 언냐들 가스라이팅 당하면 저렇게되긔  가스라이팅 개념이 대중화안돼서 잘모르는듯  그알에 가스라이팅 나올때마다 저런거 왜당하노 햇는데  가스라이팅이 얼마나 위험한건지 실감나긔  년동안 가스라이팅 존나 당했네  본인 착하다고 생각하지 않는데 초딩 때 가스라이팅 오지게 당하고  가스라이팅 주변 사람들이 뭘 어떻게 할 수 있는게 아니긔  숄 머두링 친한거 서로 가스라이팅 안하고  머두링이 세일즈 하는포인트를 국장은 가스라이팅 한거임  두달간 가스라이팅 당할때도 제정신 아니었는데  머두링 가스라이팅 존나 당한건 맞는듯  뿡 근데 회사한테 철저한 가스라이팅 받았나봐  앱 죽었을때가 살이래 연생때부터 가스라이팅 당했을텐데  남앱 뒤져서 울땐 분위기 흐리지말라고 가스라이팅 해놓고  국장이 가스라이팅 존나한듯  여니도 편입전에 가스라이팅 당해봐서 알긔  무서워했으니까 가스라이팅당해서 그렇단년들 존나좌좀마인드같애  국장 답답하다고 하는데 오랫동안 가스라이팅 당하면  머두링 그냥 이것만 봐도 가스라이팅 존나 당한거야  가스라이팅 소설  저런게 가스라이팅이구나  그 어린나이에 가스라이팅 존나 당했네  가스라이팅 그 자체노  한남 가스라이팅 잘함 음침해서 뒤통수침  솔로로 성공해야 가스라이팅 안당함  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  뿡도 가스라이팅 끝났겠노  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  깨박이 현 상태가 실검오르던 가스라이팅아니냐  억지로 묶어두려고 가스라이팅 존나 하겠지  보미는 전형적으로 김봉준한테 가스라이팅 당하고 사네   봉준이 가스라이팅의 교과서 보여주고잇네  김봉준이 채보미한테 하는짓들 다 가스라이팅임  믹테염불은 가스라이팅 당해서 소심해진거 아니노  뚱땡이는 무조건 명이 같이해야된다는 가스라이팅 작작하시긔   가스라이팅   쭈한테 가스라이팅 씹오졌노  믂도 뿡셕한테 가스라이팅 많이 당했나봐  꼴지 치열한거나 보라고 제발 가스라이팅 그만 당하고  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  가스라이팅 존나심해 뿡 병신들맞긔  지코 저새기 또 차돈 가스라이팅하네  개윤기 뿡힛한테 쳐맞고 가스라이팅 당해서 그만나댔으면  뿡힛은 직원들한테도 가스라이팅하나보긔  타요 가스라이팅 실패  믂 이번에 쳐맞고 뿡힛한테 가스라이팅 당해서  푸르때매 가스라이팅 의미 제대로 알고 간다  푸르는 공혁준한테 당한게 있어서 가스라이팅 피했네  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  근데 뿡 가스라이팅 당한거 보이지 않긔  피해자한테 가해자 왜 믿었냐고 가스라이팅 하는 곡 썼노  일어나지 않은 일로 가스라이팅 그만하고  뿡 나가면 명 다 좆된다고 가스라이팅하노  그냥 가스라이팅 당한 병신들임   믹테 꼬우면 작곡하라는말이 가스라이팅이 아니면 뭐야  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  띠니 가스라이팅 당해서 라도처럼만 안나오면 포용이기  뿡힛가스라이팅 년이면  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡은 미성년자때부터 뿡셕한테 가스라이팅 당해서  갓성은 저게 진짜 그루밍 가스라이팅 아님  뿡픽애미들 가스라이팅 노무 싫긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  뿡힛좆같은 가스라이팅 그만해  호남향우회 모르냐 라도가 뿡 가스라이팅하면서 조정해  납견이지만 지코가 푸린잉한테 하는짓은 가스라이팅임   뿡은 뿡힛가스라이팅땜에 자발적노예야  쭈 옆에서 후려치고 계속 가스라이팅하다보면  니들도 가스라이팅 조심해라   헐 맞아 가스라이팅 대표적인게 네가 예민한거야  가스라이팅이란 단어 많이 씀  뿡 가스라이팅으로 빡대갈들맞지만  뿡힛가스라이팅 지금도하잖아  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  황래혁이 여친한테 하는게 전형적인 가스라이팅임   관리하에 가스라이팅 당하고 지배당햇던거지   뿡은 뿡셕한테 가스라이팅 당한거라니까  난 뿡이 뿡힛에 가스라이팅 당한거라고도 생각했긔  알수록 뿡힛은 을위치 연생들 가스라이팅 시켜서  갤사세로 좆치질 가스라이팅하는거 신경쓰지마시긔  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  보단 낫다는게 가스라이팅이지  뿡셕이 젤 가스라이팅도 잘하고 뿡차별 젤 심해  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  막내 꾹이 분량 몰빵은 당연한걸로 가스라이팅 당함  뿡도 가스라이팅 끝났겠노  뿡 돈계산 철저하게 하면 욕심이라고 가스라이팅이라도  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  기생하려고 올뿡 가스라이팅질  억지로 묶어두려고 가스라이팅 존나 하겠지  믹테염불은 가스라이팅 당해서 소심해진거 아니노  올뿡이 왜 필요하노 뿡힛 뿡한테 가스라이팅 당하노  뿡힛에 가스라이팅 당한게 아니라 아미녀들이 지랄하는데  뿡이 가스라이팅당해서 뿡힛 나올 생각이 없으면  뿡셕 가스라이팅 심한건 다 느껴지지 않음  믂도 뿡셕한테 가스라이팅 많이 당했나봐  뿡 착한것도 가스라이팅된거니  이게 다 뿡이 가스라이팅 당한 탓이긔  라도 착하다는것도 다가스라이팅이야  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  갠활 시작하면 가스라이팅 소용없어  가스라이팅 존나심해 뿡 병신들맞긔  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  뿡힛 뿡셕 뿡 가스라이팅 존나 싸패같긔  시발 가스라이팅이 이렇게 무섭노 쭈가무능력이면  뿡힛가스라이팅 더이상 못참아  뿡 나가면 명 다 좆된다고 가스라이팅하노  가스라이팅 진짜 너무 심해  아무튼 다 가스라이팅 당해서 곡 뭐라도 써내는데  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  저번에 뿡 가스라이팅하던 직원이 이번에도 믂 꼽준거 맞긔  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡힛이랑 라도가 뿡 가스라이팅하는거 같아서  찜 뿡힛에 가스라이팅당해서 그렇긔  뿡픽애미들 가스라이팅 노무 싫긔  갑분 가스라이팅 장면 나오긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  쭈 옆에서 후려치고 계속 가스라이팅하다보면  헐 맞아 가스라이팅 대표적인게 네가 예민한거야  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  딘딘팸 나이차 많이나서 가스라이팅 오짐  분량 가스라이팅이라보 패니까 아무거나 가스라이팅이노  라도가 뿡빠기단 가스라이팅 오져 호남향우회의 전형적인  빅히트 뷔 가스라이팅 발버둥 처절하다  뿡셕 돼지새끼 이러고도 꾹 올려치기하고 찜 가스라이팅해봐  뿡셕 이새끼 보컬라인 가스라이팅 하는거 놈 티나  디패 번 터졌으면 가스라이팅 당한거지  약지슥 가스라이팅 당한다  윾정이 가스라이팅 안당하고 그 웃음 잃지 말길  근데 회사원들은 가스라이팅해야 좀 말잘듣긴하긔  근데 뿡 가스라이팅 너무 오래당해서 금방 소송 접을듯  득저씨 미친놈들이 가스라이팅해서 빻은 대표님  득저씨들 머효욕은 왜하노 가스라이팅 했으면서  역시 가스라이팅 전문 소속사 답노  숄 가스라이팅 당했을듯  숄가스라이팅 당한거긔  나 가스라이팅 존나 당하고 살았긔  띠니 어린잦 가스라이팅해서 따먹고 차였긔  숄은 누가봐도 개저씨한테 가스라이팅 당하면서  최자법 청원해주시긔 늙은한남 가스라이팅 처벌법  지가한남이니까 가스라이팅쓰면 왕따당하겠지  가스라이팅이란 단어 쓰면서 진지빨지는 마시긔  한남들이 가스라이팅에 발작하는거보니 이단어는 쓰는게맞긔  가스라이팅은 한녀로 태어났으면 무조건 당하는건데  가스라이팅이 왜 오글거린다는거긔  페미유행되기 전까지 한남한테 가스라이팅 안당해본 봊이  책안읽는데 책 많이사는거 가스라이팅이긔  노무현 사망 이런게 가스라이팅이긔  가스라이팅 잘하는 사람들은 그냥 열등감 심한거만 보면돼  가스라이팅 단어 드라마에도 나와  가스라이팅 쓰는애들 큰일나  근데 왜 가스라이팅이야  가스라이팅에 발작하는거 한남 맞네  가스라이팅 그런단어 쓰는애들 정신이상자들  가스라이팅 교양수업에나오는데  가스라이팅이 교양수업에 나왓대   가스라이팅 용어랑 상관없이 한남이 봊 후려치는거  영어단어 잘만 쓰면서 가스라이팅만 오글거리노  가스라이팅 오글거린다는 것도 가스라이팅임  아니근데 가스라이팅이란말 봊학식들 존나쓰는데  가스라이팅 싫으면 후려치기라고 해  가스라이팅 안당하려면 주위에 자랑같은거 하지마  가스라이팅을 일상에서 못쓴다는건 얼마나  쇼타 한명 가스라이팅해서 그루밍하고 싶긔  가스라이팅 오글거리는거랑 별개로 퍼지는게 봊한테 좋은건데  가스라이팅 같은게 퍼져야 최자같은 한남이 사리고다님  다른겅 몰라도 가스라이팅 맨스플레린 인플래이션이 오글거린단  가스라이팅은 성장기에 친구들한테 제일 많이 당하는것같음  맞노 빻순이짓 할때 가스라이팅 당했긔  김치국은 오지랖 라 가스라이팅이 일상이잖아  안토가 예섹 가스라이팅 해서 사겻으면 좋겟다  가스라이팅 노력한다고 안당하는거 아님  가스라이팅 아예 안당하는 사람 없음  누가 가스라이팅 시도하려고 할 때 참고하시긔  맞긔 가스라이팅 벗어나는법은 주관이 뚜렷하고  가스라이팅 어감이 너무 별로야  가스라이팅이고뭐고 그냥 만나고올때마다 기분찝찝하면 손절하는게 맞는듯  가스라이팅이라는 말 알려져서 좋은데  가스라이팅이 근본도없댄다  가스라이팅이라는 단어 혼모노같다는거   연예인들이 대부분 가스라이팅 잘당하는 그런유형의 사람들이 많음  빻은봊이 이쁜봊 가스라이팅하는것만큼 추한게 없긔  친구가 가스라이팅그게 친구노  가스라이팅 하는 새끼들 열에 아홉이  가스라이팅 잘당하는 피해자공통점이  가스라이팅 잘 당하는 사람들 특징이 뭐임  그얼굴로 가스라이팅 당한 숄 불쌍해  저 마귀할멈으로부터 윙족이 지키시긔 가스라이팅 당할라  망수 나가기 직전에 숄 보면 진짜 그 상폐남이 어떻게 가스라이팅을 했길래  잦만날때 가스라이팅 당하면 망가지긔  가스라이팅이 무슨 뜻이기  숄은 이쁜게문제가아니라 외모때문에 가스라이팅당하고  인지왜곡 시키는것 가스라이팅이긔  온냐들 잦중억 가스라이팅 하면서 호감표하는 잦알긔  읍나빛최잦 가스라이팅에 숄 좆예인인거  가스라이팅 당해서 정병심해진듯  띠니 급식때 가스라이팅당해서 씹찐따처럼 하고다녀서 찐따됐었는데  가스라이팅 썰 풀어보길래 쓴거야  약뱅노래 좋다는년들 읍죄기성적 언플에 가스라이팅 당한거야  종교는 애초부터 지배층이 가스라이팅 하는 용도였는데  가스라이팅이 모야  모성애 올려치는것도 가스라이팅임  텅텅뮤 가스라이팅 그만하시긔  김수미 할매한테 가스라이팅 당하는 대잦 내용 보고싶어  한남문학 종특은 봊 가스라이팅 안하면 연애 못함  뿡 근데 다들 가스라이팅 당하고 정병라 잘 꼬시면 띠니도 사귈수있을듯  남의식 약간 은따나 가스라이팅 많이 당하면 그렇게됨  언냐들 가스라이팅 조심해   휴메띠니 가스라이팅 하고싶긔  결혼하고 독박살림에 가스라이팅 존나 당한거면  저거도 구줌이 필터링한거 같긔 더 심한 말도 하면서 가스라이팅했노  구혜선 가스라이팅한 한국남자 면상  한녀들 와꾸 지나치게 안 보는 것도 가스라이팅 당한것 같아  년동안 남동충 가스라이팅시켜서 집안일떠맡겼긔  갓파 살때부터 납치해서 가스라이팅 존나 한다음에  흰수만 꾸니 트름랩에 가스라이팅 당하고 있나봐  가스라이팅 당하는 의뚝이  스스로 가스라이팅 미쳤노  뿡은 맨날 가스라이팅 하니까 허허충에 발작하는거긔  윽신이 봊친한테 가스라이팅 잘할거같음  일단 한남들이 만든 영화 모든게 다 봊들 가스라이팅시키고 기죽일려고  왜 좁이 주위엔 좁이 가스라이팅해줄 사람이 없을까  뿡 행복충아니긔 요새 가스라이팅당하고 불행충이었긔  찜 오늘 뮤뱅엔딩 영상으로 가스라이팅 오지게 당하겠노  삐에게 가스라이팅하는 한남 믂  딱쭈는 딱이가 쭈 가스라이팅 시도하다가  좁스부치언니 딱갤주 가스라이팅 성공한듯  김랩괴 가스라이팅 해서라도 갖고만다  딱이 좁이보고 코르셋조이라고 가스라이팅하다가  한녀들 그냥 단체로 정신병왓다니깐 하도 가스라이팅당해서  뿡는 가스라이팅 흙수저타령 명품백타령 안해서 좋긔  하괴윙족문학 가스라이팅  근데 한남한테 가스라이팅 당하면 존나좆같겟다  좁이 누가 가스라이팅 좀 해  혐애미들 존아 명잦이다 가스라이팅 중  짐승한테까지 가스라이팅 당해서 지 재산 쏟아붓는 병신년들  언냐 친구들이 가스라이팅하노  김주영 가스라이팅 최고긔  살면서 가스라이팅하고만 살아올것같은게 꾹인데  뿡은 꾹빼고 한남 가스라이팅 오져  언냐들 가스라이팅에 넘어가지좀 마시긔  서키 맘에드는 젊은 봊 있으면 가스라이팅 오지게했을듯  존나 능글거리면서 대놓고 가스라이팅하는 한남 존나싫어  가스라이팅 대놓고 하는 한남 볼때 존나 빡쳐  씹가위년들 한남 빙의해서 봊한테 가스라이팅 존나 해  띠니 가스라이팅 뜻 이제 알았오  퀸주영 가스라이팅   가스라이팅 하고싶어  가스라이팅 존나당하면 진짜 정신 이상해지는거같애  새내기시발련 가스라이팅 존나해서 좆생 망가뜨릴거야  가스라이팅이라는 단어랑 뿌주부랑 같은 문장에 잇는게 왤케 웃기지  뿌주부 가스라이팅 기술 라고 느꼇던거  가스라이팅깅  씹댕청한 잘생긴 잦 예쁜 봊 가스라이팅깅 하고싶기  가스라이팅이 뭐긔  띤갤언냐들 가스라이팅해서 띠니 시녀로 만들고싶긔  변요한띠니도 가스라이팅 당함  가스라이팅도 사랑인데 노무 왜곡하지는 마시긔  띠니는 가스라이팅과 사랑을 동일시하게 생각하긔  좆간대할때 이런생각 한번이라도 햇으면 가스라이팅 당한거야  가스라이팅 왕진진이 낸시랭한테도하던데  직장상사가 가스라이팅하는데 칼빵찌르고싶었긔  으누가 가스라이팅해주면 좋겠다 헌법으로 만들어야됨  가스라이팅 당하는년들 솔직히 지들도 알고잇긔  자기얘기만 안 해도 거의 가스라이팅 당할일 없긔  가스라이팅 당하는년들 특 분명 잘못해서 화냇는데 불안함  가스라이팅 유래 이거긔  가스라이팅 당사자말고 가해자일땐 진짜 존나재밋어  인싸새내기들 머갈통 쳐빻아서 가스라이팅해도 몰라  인싸새내기 씹입생들 가스라이팅 맨스플레인 하고싶긔  진짜 봊이면 대쉬 못받는다는것도 한남들 가스라이팅이긔  와꾸아니라도 빨거있는 새끼는 가스라이팅을 존나 해야됨  딱갤주가 좁깅이 머리로 후려치고 가스라이팅하는거 보고싶긔  제발 딱이가 좁이 옆에두고 가스라이팅 존나 했으면  똥미노 부랄에다 기름붓고 가스라이팅하고싶긔노윤딱  김경수 가스라이팅 존나 잘하게 생김  난 오히려 윰멍이 자기도 가스라이팅 피해자고  생각해보니까 윰댕도 김이브한테 가스라이팅당해서 몇년동안 끌려다녔잖아  좁이는 왜 가스라이팅도 안당하노  좁이 머리자르지말라는게 왜가스라이팅이긔  부니 머리로 가스라이팅 좀 당해야돼  머큐리 게이매니저가 가스라이팅 한거같은데  가스라이팅으로 흙수저 컨셉 잡아놓고 돈버니까 명품휘두르고다님  좁이 누가 가스라이팅 좀 하라고  앙준이 댕청해서 가스라이팅하고싶자나  트페미들아 니네 좌빨한테 가스라이팅 당한건 암  트페미들이 하는게 가스라이팅이긔  양아치 폰팔이 훈남한테 가스라이팅 당해서 동거하고 싶다  양남은 잦으로 안 보인다는것도 가스라이팅 당한거긔  한남친구한테 가스라이팅했는데  개독 가스라이팅인생 최후의 행복회로  봉랑이 가스라이팅 존나 잘할거같음  갓파 가스라이팅하기 최적화 아니긔  앙준이 가스라이팅 하면서 사귀고 싶어   한남들 가스라이팅해서 꼬무룩하게 만드는 법은   연하남 가스라이팅하면서 만나고싶긔  이오빠한테 가스라이팅 당하고싶다  근데 왜 한남새끼들은 와꾸도 고추도 좆빻은게 가스라이팅이 일상화되있음  가스라이팅하는방법  가스라이팅이고 지랄이고 작작싸워 미친년들아  트페미 시발년들 가스라이팅 뜻은 제대로 알고 말하는거노  내가 실제로봤던 가스라이팅 하나밖에없음  가스라이팅 좆돌새끼들한테 하면   가스라이팅 설명하는 년이 설명을 잘못했네  가스라이팅으로 한남패니까 이지랄난거잖아  가스라이팅플도 그냥 한마음으로 한남 패면 되는데  가스라이팅이 뭔데 가스에 불붙듯 서서히 유혹하는거임  가스라이팅이 걍 후려친다기 보다는 닌 나없으면  가스라이팅이라는건 정말 멍청하면 못하는짓인건 맞음  의견다른걸 억지로 세뇌시키는게 가스라이팅이라며  가스라이팅 영어단어있다니까 이거 이야 트페미용어아님  왜또 가스라이팅갤이냐 이기야  가스라이팅 얘기한지 얼마나됐다고 발작하는 이유가 뭐긔  트페미 시발년들아 니네가 가스라이팅 트리거를  서창빈 가스라이팅 해서 은퇴시키고 싶다  가스라이팅 좌좀들이잘함  가스라이팅 당했네 이러는거 솔직히 폭토커가 지 싸패라 그러는거 보는 기분  새끼 가스라이팅하고싶다  가스라이팅이라는 단어에 발작하는 이유  나 좆이콘한테 가스라이팅 당햇긔  가스라이팅은 후려치기랑은 조금 다른느낌  맨날 앰한테 가스라이팅당하는데 자존감 안떨어짐  김치국에서 가스라이팅 안 당하는 봊이 없을텐데  가스라이팅 이지랄하는거 존나 트페미같다  가스라이팅말고 동숲갤하자  가스라이팅인가 그딴거 미자때 아님 당하는거 존나 이해안됨  가스라이팅말고 다른말없노 존나 트페미같아  왜 갑자기 가스라이팅 갤이긔  가스라이팅이 뭔데  전라도 남자들이 가스라이팅을 잘함  가스라이팅이 존나 무서운게 봊이 뒤질때까지 쳐맞고도  글고 가스라이팅이 진짜 무서운게 어떻게 그 무리에서  잦친한테 가스라이팅 당하는 봊도 진짜 이상한게  우리나라 전체가 봊상대로 가스라이팅 한다는거 맞음  가스라이팅하는 한남들 강약약강임  가스라이팅 걸릴 새끼만 걸린단건 뻘소리긔  가스라이팅 방법중에 하나 이거라하긩  존나 가까운 사람이 가스라이팅 했다고 생각해봐  가스라이팅 저거 어원도 만 걸려드는거 맞네  가스라이팅이 머임 나도 할래  존나긴반고닉이 나한테 자꾸 시비거는것도 가스라이팅이긔  호모문학에 트리거 가스라이팅 이러는거 존나같잖아  가스라이팅 우리애미가 존나잘해  가스라이팅 어원 존나 소름돋긔  가스라이팅도 당해본 사람이 잘함  가스라이팅 동등한관계보다 수직관계에서 잘먹힐듯  가스라이팅이 페미용어래도 저정도는 인식하고 있어야하긔  가스라이팅에서 벗어나는건 쉬울거같음  가스라이팅 자존감낮은 머리좋은애들이잘함  가스라이팅 트페미용어 맞음  가스라이팅 존나 잘하는 년들이 있긔  저 태국똥냐옵 구해줘야 되는 거 아님 가스라이팅 당하는 중인 것 같아  시녀들 지가빠는 봊돌 라고 가스라이팅 시동거는거 토나와  보다보면 잘생겼다 이거 착즙이나 가스라이팅 둘 중하나임  마시도 그렇고 안토도 그렇고 나는 꾸며도 안된다고 가스라이팅 된 봊들 불쌍해  으누가 가스라이팅 하는건 그냥 사랑이지  은우한테 가스라이팅 당하고 싶어  으누한테는 가스라이팅 당하고 싶어  난 은오후 가스라이팅 하고싶긔  앙준이 가스라이팅하고싶어  가스라이팅 호모웹툰없노  방탄 아미한테 가스라이팅 오지게 하네  며느리에게 가하는 가스라이팅  가스라이팅 예시 아는 사람  친구년 하는 짓 가스라이팅 맞지  나 가스라이팅 해봐  이것도 가스라이팅이라고 할   가스라이팅 당하는 거 같아요  상식 가스라이팅에 대해서 알아보자 똑똑한 병신들만 클릭 
"""

In [298]:
t = Tokenizer()
t.fit_on_texts([text1])
vocab_size = len(t.word_index) + 1
# 케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야하므로 미리 +1 선언 
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 1581


In [299]:
t.word_index

{'가스라이팅': 1,
 '존나': 2,
 '가스라이팅이': 3,
 '뿡': 4,
 '한남': 5,
 '근데': 6,
 '가스라이팅으로': 7,
 '당한거야': 8,
 '뿡이': 9,
 '그냥': 10,
 '당해서': 11,
 '진짜': 12,
 '가스라이팅당해서': 13,
 '당하고': 14,
 '년간': 15,
 '막내푸쉬': 16,
 '뿡은': 17,
 '가스라이팅해서': 18,
 '하는': 19,
 '당하는': 20,
 '가스라이팅에': 21,
 '다': 22,
 '왜': 23,
 '당한': 24,
 '가스라이팅은': 25,
 '좀': 26,
 '단어': 27,
 '가스라이팅이라는': 28,
 '뿡힛': 29,
 '나': 30,
 '많이': 31,
 '언냐들': 32,
 '띠니': 33,
 '머두링': 34,
 '국장': 35,
 '그': 36,
 '당하면': 37,
 '뿡셕': 38,
 '당한거긔': 39,
 '가스라이팅이긔': 40,
 '좁이': 41,
 '당함': 42,
 '오지게': 43,
 '봊': 44,
 '당한거': 45,
 '누가': 46,
 '한남들': 47,
 '노무': 48,
 '가스라이팅도': 49,
 '숄': 50,
 '뿡셕이': 51,
 '케어': 52,
 '가스라이팅임': 53,
 '년동안': 54,
 '가스라이팅하는': 55,
 '저': 56,
 '한남한테': 57,
 '봊이': 58,
 '아니노': 59,
 '그만해': 60,
 '같아': 61,
 '가스라이팅하는거': 62,
 '맞음': 63,
 '걍': 64,
 '하면서': 65,
 '케어로': 66,
 '뿡셕한테': 67,
 '젤': 68,
 '아님': 69,
 '가스라이팅을': 70,
 '안': 71,
 '있는데': 72,
 '불쌍해': 73,
 '거': 74,
 '자존감': 75,
 '놈': 76,
 '나한테': 77,
 '없긔': 78,
 '아니긔': 79,
 '한남이': 80,
 '가스라이팅하면서': 81,
 '라고': 82,
 '하고싶어': 83,
 '빅히트가

In [300]:
text3 = list()
for line in text1.split('  '):
    text3.append(line)

In [301]:
# sequences = list()
# encoded = t.texts_to_sequences([text3[0]])[0] 
# encoded

[291, 292, 18, 293, 294]

In [306]:
# sequences = list()
# r_sequences = list()
# for i in range(1, len(encoded)):
#     sequence = encoded[(len(encoded)-i-1):]
#     sequences.append(sequence)
# for i in sequences:
#     r_sequences.append(list(reversed(i)))

In [307]:
# r_sequences

[[294, 293], [294, 293, 18], [294, 293, 18, 292], [294, 293, 18, 292, 291]]

In [303]:
# sequences

[[293, 294], [18, 293, 294], [292, 18, 293, 294], [291, 292, 18, 293, 294]]

In [311]:
sequences = list()
r_sequences = list()
for line in text3: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[(len(encoded)-i-1):]
        sequences.append(sequence)
for i in sequences:
    r_sequences.append(list(reversed(i)))

len(r_sequences)

2076

In [312]:
max_len=max(len(l) for l in sequences)
r_sequences = pad_sequences(r_sequences, maxlen=max_len, padding='pre')

In [313]:
r_sequences

array([[   0,    0,    0, ...,    0,  294,  293],
       [   0,    0,    0, ...,  294,  293,   18],
       [   0,    0,    0, ...,  293,   18,  292],
       ...,
       [   0,    0,    0, ..., 1578, 1577, 1576],
       [   0,    0,    0, ..., 1577, 1576,   21],
       [   0,    0,    0, ..., 1576,   21, 1575]])

In [317]:
r_sequences = np.array(r_sequences)
# X = sequences[:,1:]
# y = sequences[:,:1]
X = r_sequences[:,:-1]
y = r_sequences[:,-1]

In [318]:
y

array([ 293,   18,  292, ..., 1576,   21, 1575])

In [319]:
X

array([[   0,    0,    0, ...,    0,    0,  294],
       [   0,    0,    0, ...,    0,  294,  293],
       [   0,    0,    0, ...,  294,  293,   18],
       ...,
       [   0,    0,    0, ..., 1579, 1578, 1577],
       [   0,    0,    0, ..., 1578, 1577, 1576],
       [   0,    0,    0, ..., 1577, 1576,   21]])

In [320]:
y = to_categorical(y, num_classes=vocab_size)

In [328]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 10, 10)            15810     
_________________________________________________________________
lstm_7 (LSTM)                (None, 128)               71168     
_________________________________________________________________
dense_8 (Dense)              (None, 1581)              203949    
Total params: 290,927
Trainable params: 290,927
Non-trainable params: 0
_________________________________________________________________


In [321]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, verbose=2)

Epoch 1/150
65/65 - 1s - loss: 7.0208 - accuracy: 0.1498
Epoch 2/150
65/65 - 1s - loss: 6.3839 - accuracy: 0.1527
Epoch 3/150
65/65 - 1s - loss: 6.2556 - accuracy: 0.1527
Epoch 4/150
65/65 - 1s - loss: 6.1623 - accuracy: 0.1527
Epoch 5/150
65/65 - 1s - loss: 6.0772 - accuracy: 0.1527
Epoch 6/150
65/65 - 1s - loss: 5.9972 - accuracy: 0.1527
Epoch 7/150
65/65 - 1s - loss: 5.9308 - accuracy: 0.1527
Epoch 8/150
65/65 - 1s - loss: 5.8612 - accuracy: 0.1527
Epoch 9/150
65/65 - 1s - loss: 5.7842 - accuracy: 0.1527
Epoch 10/150
65/65 - 1s - loss: 5.6747 - accuracy: 0.1546
Epoch 11/150
65/65 - 1s - loss: 5.5390 - accuracy: 0.1570
Epoch 12/150
65/65 - 1s - loss: 5.3960 - accuracy: 0.1594
Epoch 13/150
65/65 - 1s - loss: 5.2484 - accuracy: 0.1647
Epoch 14/150
65/65 - 1s - loss: 5.1036 - accuracy: 0.1657
Epoch 15/150
65/65 - 1s - loss: 4.9565 - accuracy: 0.1739
Epoch 16/150
65/65 - 1s - loss: 4.8161 - accuracy: 0.1773
Epoch 17/150
65/65 - 1s - loss: 4.6856 - accuracy: 0.1855
Epoch 18/150
65/65 - 1s

Epoch 142/150
65/65 - 1s - loss: 1.0101 - accuracy: 0.7664
Epoch 143/150
65/65 - 1s - loss: 0.9994 - accuracy: 0.7635
Epoch 144/150
65/65 - 1s - loss: 0.9903 - accuracy: 0.7649
Epoch 145/150
65/65 - 1s - loss: 0.9808 - accuracy: 0.7707
Epoch 146/150
65/65 - 1s - loss: 0.9719 - accuracy: 0.7707
Epoch 147/150
65/65 - 1s - loss: 0.9631 - accuracy: 0.7712
Epoch 148/150
65/65 - 1s - loss: 0.9514 - accuracy: 0.7746
Epoch 149/150
65/65 - 1s - loss: 0.9420 - accuracy: 0.7775
Epoch 150/150
65/65 - 1s - loss: 0.9313 - accuracy: 0.7842


In [349]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=11, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word =  current_word + ' '  + word  # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word  # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [350]:
print(sentence_generation(model, t, '가스라이팅', 4))

가스라이팅 나 뿡들은 입털고 솔로라고


In [326]:
print(sentence_generation(model, t, '가스라이팅이', 3))

가스라이팅이 기죽여놓고 가스라이팅으로 빅히트가


In [384]:
text1 = """
잦동충은 유충때부터 가스라이팅해서 기 눌러놔야됨  잦동충 있는년들 띵잦이 많긔 앰앱한테 가스라이팅 당함  잦동생 한명 있는데 어릴때부터 가스라이팅 시켰더니 긔  잘생긴 잦 묶어놓고 존나패고 가스라이팅하고싶으면 이상성욕이긔  나래코기랑 도연언냐는 나래코기가 가스라이팅한거긔  몇백년동안 가스라이팅 당한 한녀 불쌍해  머학 새내기때 가스라이팅 당하기 존나 쉬워   전래동화라면서 좆기때부터 가스라이팅시키노  토마토 가스라이팅 당한 거 맞지  봊초년들특징이 그냥 팩트말하면 가스라이팅이라함  와 가스라이팅 가스라이팅 말만 듣고 뜻만 알았지  족구 군대간 년동안 가축들이 가스라이팅 당함  봉준이방송은 가스라이팅방송임  지금 케이는 가스라이팅 중임  딱 여자들이 좋아하는 단어 가스라이팅 오지게 당한거지 푸르는  최군은 가스라이팅 잘하지  사실 방송 별거 아닌데 혜디주변에서 혜디 가스라이팅하는게 참  어릴때부터 가스라이팅 당해서 자존감 하나도 없어  개딱단과 개엑이야 말로 가스라이팅 한거긔  김극라는 가스라이팅하는 봊 만나야해  혹시 공주 가스라이팅 당한거 아닐까윤  저 말한 놈 그단톡방에서 가스라이팅 당한거같긔  여니 잇팁인데 가스라이팅이라는 단어 이해안됨  뿡힛 가스라이팅이 믹테야 적어도 보컬한테는  씹매들시대엔 봊기때부터 가스라이팅해서 살때  중딩때 나한테 오지게 가스라이팅한년 죽이고싶어  빻다빠는년들 가스라이팅 잘당할것같긔  현실에서 가스라이팅 병신끼리 주고받지 않노  가스라이팅 당하고살긔  하 시발 가스라이팅 인 새끼 있는데  나 가스라이팅 존나 당함  누가 나 가스라이팅 시도한적 없긔  는 가스라이팅 절대 안당함  가스라이팅 문장 저거 한남들 단골멘트 아니긔  한남한테 가스라이팅하면 한남이 나한테 의지해서  한남한테 가스라이팅해보고싶노  띠닌 인데 가스라이팅 이해가긔  가스라이팅 이해 안가는 언냐  잇팁 가스라이팅 이해 안간다는거 딱 한남같노   인데 가스라이팅 당하는거 존나 이해안가긔  발삼이 잦스틴이 가스라이팅 시켜놨으니까 놔줘  한남 좃 웃긴거 누가 널 만나주냐는 식으로 가스라이팅하면서  한녀들은 한남 존나싫다는데 왤케 가스라이팅하는거노  라도춤은 뿡힛식 강제 가스라이팅이지 라도춤이 어디서  망망프다이어리 녕동민 가스라이팅 너무당해서  스시잦들 투잡가스라이팅대리효도없는것만으로도 라고 생각했었는데  한녀들이 당한 역대급 가스라이팅은 반일선동이라고 생각해  황발삼 가스라이팅 하고싶어  빅히트가 개인방 몇명만 준거 가스라이팅 이긔  의새도 환자 가스라이팅 하는 의새 개많아  미동이가 윾나 가스라이팅하려는거같애서 놈 혐오스럽긔  가스라이팅 단어도 변질됨  잦친한테 자격지심들고 가스라이팅 당한거 생각하면 노무 분해  빻다 옆에서 못생겼다고 가스라이팅 시킬 봊이 필요함  메리는 가스라이팅 안통할 것 같긔  강섹훈 가스라이팅 존나 시키고 싶긔  나 감쓰삼고 가스라이팅하던 틀딱년들 손절했는데  혐애할때 유독 한녀들만 가스라이팅 존나당하는거 같긔  득팔이 노무 못생겼기도 하고 주변에서 가스라이팅 많이 당했을긋  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  진심 성형 보편화 된거 한남 가스라이팅 아니노  봊친한테 휘둘리며 가스라이팅 당하는 딘쿵야  녀살려야 아메한테 가스라이팅 그만해  가스라이팅 당한 봊자식은 사실 제대로 반항도 못해  이런갤열면 앰생한남들 기어들어와서 가스라이팅 시작함  근데 울앰 가스라이팅 장인 같아  느그랑 가스라이팅 먹힐 성격같긔  인간들 혐오스러워 가스라이팅 오지고  언냐들 한남 가스라이팅 도와주시긔  정냐는 가스라이팅 하고싶어도 이미 병 든 장혜인 상태라  찐따한남 특 착하고 친절한 봊한테 가스라이팅 존나 함  한남 가스라이팅시키니까기분딱좋노  짭멘갑 같은 새끼들한테 은근슬적 가스라이팅 얹어줘야함  원넨 참치 특징 애미가 가스라이팅 잘시킴  솔직히 한남조심하는건 가스라이팅아니긔  가스라이팅해봤자 한녀들은 토모토모보고 있는데  식민지남성들 주제에 가스라이팅하는거 추하긔  봊들이 혐혼안한다하면 가스라이팅 해대는거 씹  살자 말리는 년들 대부분 김치국이 가스라이팅시킨거라  멘탈 라 한남들 사귈때 가스라이팅으로 살자마려웠는데  띠니 가스라이팅 당했나봄  앰버온냐 대단한게 조니뎁 상대로 가스라이팅함  머두링 가스라이팅당한게 국장 탈퇴감은 아니긴 함  발삼이는 키안커서 가스라이팅에 최적화 되어있긔  트페미들은 왜이리 가스라이팅이라는 단어를 좋아함  가스라이팅때문에 푸르랑 쏘가 욕먹는줄 아는애들이  윾나 진짜로 미동이한테 가스라이팅 당하는중  황발삼 가스라이팅해서 집착하게 만들고 싶긔  딱이가 종삽이 음악적 가스라이팅 함  민주당 저렇게 플랜카드 거는거 가스라이팅 아니노  김치인 종특이 가스라이팅 잘하는거같오  각슬이 이모한테 가스라이팅 당한거 같아  토마토는 가스라이팅 당한거 맞음 그 돼지새끼  잦동생있으면 가스라이팅로 세뇌 존나 시켜야돼  옐무 이거 코디가 가스라이팅한거같긔  덕혜옹주 가스라이팅당한것같음  마토 가스라이팅  토마토 가스라이팅 당했냐  숙달이 걍 주변배슬아재들한테 가스라이팅당해서  헬트한남들 가스라이팅 존나해대면서 피티 연장하라고  흙수저앰앱은 자식 가스라이팅도 많이함  가스라이팅 필터링 뿡라이팅으로 변경합니다  기타갑 주변인들 질투심때문에 존나 가스라이팅했을듯  근데 가스라이팅이란말도 웃기지 않긔  악플러라고 왜패옛날에 띤갤에서 가스라이팅 당한건데  이제 나쁜짓 하다 걸리면 심신미약대신 가스라이팅 타령할듯  앞으론 살인자옆에서 동조하고도 가스라이팅 당했다고 하면될듯  떠려니는 가스라이팅이 아니라 그냥 국장한테 붙어먹는 꼬봉이지  가스라이팅 당했다고 떠려니 또다른 피해자로 만드는거 정말 재밌어  담배갑 탈미는 국장 가스라이팅 안당했는데  띠니는 살때 찐따년 가스라이팅했긔  설현은 가스라이팅에 최적화된 스타일이네  페미 공부 하면서 가스라이팅이 뭔지도 알텐데  떠려니가 가스라이팅 당했다는게 웃긴 이유  근데 떠려니도 국장 가스라이팅에 좀 당한것같은데  찐오아 가스라이팅 당했다 하는 시녀들 나가죽어그냥   국쟝님 이번 일이 화나는건 갈굼 손찌검 가스라이팅 다 있어서가 아닐까  가스라이팅 하다가 도망간 봊친앞에서 칼들고 협박하는 한남  국장 그냥 전형적인 가스라이팅 하는 사람중 하나인듯  국장년 역가스라이팅 하고싶다   가스라이팅했노  뭘 가스라이팅이야  저게 진짜 가스라이팅 아니냐  가스라이팅이 저래서 무서운거긔  머두링 이미 가스라이팅 라 더 안타까워보이는거  떠려니가 가스라이팅 당했다노 시녀들 돌았나봐  우리 앰이랑 언니년이 저런 가스라이팅 잘하긔  머두링 글 보니깐 저 사람들 직접 찾아와서 가스라이팅 존나 했네  칼들고 난리친거 진짜 데이트폭력 가스라이팅 한남 그자체  국장 가스라이팅 관련해서 뭐 참고하는 수준이노  가스라이팅 당해본 온냐있노  멤버가 모를수가없긔 같이 가스라이팅당했든 방관했든  가스라이팅하는애들은 지좋아하는애한테는  한남들끼리 가스라이팅 존나 많아  후햄이 믂가한테 가스라이팅 하는방법 가르쳐줄것같긔  떠려니 절친이면 그냥 닥치지 국장한테 가스라이팅  국장처럼 문재앙 가스라이팅 하고싶어  가스라이팅 기세도 당할 수 있음  국장이 떠려니도 존나 가스라이팅했긔  가스라이팅은 똑똑한봊도 많이당함  가스라이팅 당하면 자존감 바닥찍기  년동안 가스라이팅이면 사람 바뀔수준임  근데 가스라이팅이 로 무섭긴 하노  저렇게 가스라이팅하는놈들 습관이라  성격 순한 언냐들 가스라이팅 당하면 저렇게되긔  가스라이팅 개념이 대중화안돼서 잘모르는듯  그알에 가스라이팅 나올때마다 저런거 왜당하노 햇는데  가스라이팅이 얼마나 위험한건지 실감나긔  년동안 가스라이팅 존나 당했네  본인 착하다고 생각하지 않는데 초딩 때 가스라이팅 오지게 당하고  가스라이팅 주변 사람들이 뭘 어떻게 할 수 있는게 아니긔  숄 머두링 친한거 서로 가스라이팅 안하고  머두링이 세일즈 하는포인트를 국장은 가스라이팅 한거임  두달간 가스라이팅 당할때도 제정신 아니었는데  머두링 가스라이팅 존나 당한건 맞는듯  뿡 근데 회사한테 철저한 가스라이팅 받았나봐  앱 죽었을때가 살이래 연생때부터 가스라이팅 당했을텐데  남앱 뒤져서 울땐 분위기 흐리지말라고 가스라이팅 해놓고  국장이 가스라이팅 존나한듯  여니도 편입전에 가스라이팅 당해봐서 알긔  무서워했으니까 가스라이팅당해서 그렇단년들 존나좌좀마인드같애  국장 답답하다고 하는데 오랫동안 가스라이팅 당하면  머두링 그냥 이것만 봐도 가스라이팅 존나 당한거야  가스라이팅 소설  저런게 가스라이팅이구나  그 어린나이에 가스라이팅 존나 당했네  가스라이팅 그 자체노  한남 가스라이팅 잘함 음침해서 뒤통수침  솔로로 성공해야 가스라이팅 안당함  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  뿡도 가스라이팅 끝났겠노  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  깨박이 현 상태가 실검오르던 가스라이팅아니냐  억지로 묶어두려고 가스라이팅 존나 하겠지  보미는 전형적으로 김봉준한테 가스라이팅 당하고 사네   봉준이 가스라이팅의 교과서 보여주고잇네  김봉준이 채보미한테 하는짓들 다 가스라이팅임  믹테염불은 가스라이팅 당해서 소심해진거 아니노  뚱땡이는 무조건 명이 같이해야된다는 가스라이팅 작작하시긔   가스라이팅   쭈한테 가스라이팅 씹오졌노  믂도 뿡셕한테 가스라이팅 많이 당했나봐  꼴지 치열한거나 보라고 제발 가스라이팅 그만 당하고  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  가스라이팅 존나심해 뿡 병신들맞긔  지코 저새기 또 차돈 가스라이팅하네  개윤기 뿡힛한테 쳐맞고 가스라이팅 당해서 그만나댔으면  뿡힛은 직원들한테도 가스라이팅하나보긔  타요 가스라이팅 실패  믂 이번에 쳐맞고 뿡힛한테 가스라이팅 당해서  푸르때매 가스라이팅 의미 제대로 알고 간다  푸르는 공혁준한테 당한게 있어서 가스라이팅 피했네  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  근데 뿡 가스라이팅 당한거 보이지 않긔  피해자한테 가해자 왜 믿었냐고 가스라이팅 하는 곡 썼노  일어나지 않은 일로 가스라이팅 그만하고  뿡 나가면 명 다 좆된다고 가스라이팅하노  그냥 가스라이팅 당한 병신들임   믹테 꼬우면 작곡하라는말이 가스라이팅이 아니면 뭐야  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  띠니 가스라이팅 당해서 라도처럼만 안나오면 포용이기  뿡힛가스라이팅 년이면  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡은 미성년자때부터 뿡셕한테 가스라이팅 당해서  갓성은 저게 진짜 그루밍 가스라이팅 아님  뿡픽애미들 가스라이팅 노무 싫긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  뿡힛좆같은 가스라이팅 그만해  호남향우회 모르냐 라도가 뿡 가스라이팅하면서 조정해  납견이지만 지코가 푸린잉한테 하는짓은 가스라이팅임   뿡은 뿡힛가스라이팅땜에 자발적노예야  쭈 옆에서 후려치고 계속 가스라이팅하다보면  니들도 가스라이팅 조심해라   헐 맞아 가스라이팅 대표적인게 네가 예민한거야  가스라이팅이란 단어 많이 씀  뿡 가스라이팅으로 빡대갈들맞지만  뿡힛가스라이팅 지금도하잖아  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  황래혁이 여친한테 하는게 전형적인 가스라이팅임   관리하에 가스라이팅 당하고 지배당햇던거지   뿡은 뿡셕한테 가스라이팅 당한거라니까  난 뿡이 뿡힛에 가스라이팅 당한거라고도 생각했긔  알수록 뿡힛은 을위치 연생들 가스라이팅 시켜서  갤사세로 좆치질 가스라이팅하는거 신경쓰지마시긔  괴 지는 솔로라고 입털고 뿡들은 단체여야한다고 가스라이팅  보단 낫다는게 가스라이팅이지  뿡셕이 젤 가스라이팅도 잘하고 뿡차별 젤 심해  그거 뿡셕 어제 봤는데 뿡셕이 비저씨 존나 가스라이팅했대긔  막내 꾹이 분량 몰빵은 당연한걸로 가스라이팅 당함  뿡도 가스라이팅 끝났겠노  뿡 돈계산 철저하게 하면 욕심이라고 가스라이팅이라도  빅히트가 가스라이팅으로 기죽여놓고 찜쭈  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어로 가스라이팅 당한거야  뿡이 년간 막내푸쉬 케어 가스라이팅 당한거야  기생하려고 올뿡 가스라이팅질  억지로 묶어두려고 가스라이팅 존나 하겠지  믹테염불은 가스라이팅 당해서 소심해진거 아니노  올뿡이 왜 필요하노 뿡힛 뿡한테 가스라이팅 당하노  뿡힛에 가스라이팅 당한게 아니라 아미녀들이 지랄하는데  뿡이 가스라이팅당해서 뿡힛 나올 생각이 없으면  뿡셕 가스라이팅 심한건 다 느껴지지 않음  믂도 뿡셕한테 가스라이팅 많이 당했나봐  뿡 착한것도 가스라이팅된거니  이게 다 뿡이 가스라이팅 당한 탓이긔  라도 착하다는것도 다가스라이팅이야  년차 뿡인데 가스라이팅으로 아직 년도 뿡같긔  가스라이팅 좀 그만해  갠활 시작하면 가스라이팅 소용없어  가스라이팅 존나심해 뿡 병신들맞긔  가스라이팅 안당하면 어쩌란거긔 친구도 아니고 회사인데  뿡힛 뿡셕 뿡 가스라이팅 존나 싸패같긔  시발 가스라이팅이 이렇게 무섭노 쭈가무능력이면  뿡힛가스라이팅 더이상 못참아  뿡 나가면 명 다 좆된다고 가스라이팅하노  가스라이팅 진짜 너무 심해  아무튼 다 가스라이팅 당해서 곡 뭐라도 써내는데  뿡은 걍 딴생각 못하게 가스라이팅 당한거긔  가스라이팅 년이야  뿡은 가스라이팅으로 이용만당하다 군지하고  저번에 뿡 가스라이팅하던 직원이 이번에도 믂 꼽준거 맞긔  가스라이팅 딴좆돌도 저러노  뿡 존나 가스라이팅당해서  언냐들도 가스라이팅 당한거긔  언냐들 가스라이팅은 뿡셕이 젤 심했긔  뿡힛이랑 라도가 뿡 가스라이팅하는거 같아서  찜 뿡힛에 가스라이팅당해서 그렇긔  뿡픽애미들 가스라이팅 노무 싫긔  갑분 가스라이팅 장면 나오긔  찜뚜니 가스라이팅잘먹힐거같  가스라이팅때문인지  쭈 옆에서 후려치고 계속 가스라이팅하다보면  헐 맞아 가스라이팅 대표적인게 네가 예민한거야  뿡 뭣도 모를때 뿡힛 가스라이팅으로 지금까지 잘했잖아  딘딘팸 나이차 많이나서 가스라이팅 오짐  분량 가스라이팅이라보 패니까 아무거나 가스라이팅이노  라도가 뿡빠기단 가스라이팅 오져 호남향우회의 전형적인  빅히트 뷔 가스라이팅 발버둥 처절하다  뿡셕 돼지새끼 이러고도 꾹 올려치기하고 찜 가스라이팅해봐  뿡셕 이새끼 보컬라인 가스라이팅 하는거 놈 티나  디패 번 터졌으면 가스라이팅 당한거지  약지슥 가스라이팅 당한다  윾정이 가스라이팅 안당하고 그 웃음 잃지 말길  근데 회사원들은 가스라이팅해야 좀 말잘듣긴하긔  근데 뿡 가스라이팅 너무 오래당해서 금방 소송 접을듯  득저씨 미친놈들이 가스라이팅해서 빻은 대표님  득저씨들 머효욕은 왜하노 가스라이팅 했으면서  역시 가스라이팅 전문 소속사 답노  숄 가스라이팅 당했을듯  숄가스라이팅 당한거긔  나 가스라이팅 존나 당하고 살았긔  띠니 어린잦 가스라이팅해서 따먹고 차였긔  숄은 누가봐도 개저씨한테 가스라이팅 당하면서  최자법 청원해주시긔 늙은한남 가스라이팅 처벌법  지가한남이니까 가스라이팅쓰면 왕따당하겠지  가스라이팅이란 단어 쓰면서 진지빨지는 마시긔  한남들이 가스라이팅에 발작하는거보니 이단어는 쓰는게맞긔  가스라이팅은 한녀로 태어났으면 무조건 당하는건데  가스라이팅이 왜 오글거린다는거긔  페미유행되기 전까지 한남한테 가스라이팅 안당해본 봊이  책안읽는데 책 많이사는거 가스라이팅이긔  노무현 사망 이런게 가스라이팅이긔  가스라이팅 잘하는 사람들은 그냥 열등감 심한거만 보면돼  가스라이팅 단어 드라마에도 나와  가스라이팅 쓰는애들 큰일나  근데 왜 가스라이팅이야  가스라이팅에 발작하는거 한남 맞네  가스라이팅 그런단어 쓰는애들 정신이상자들  가스라이팅 교양수업에나오는데  가스라이팅이 교양수업에 나왓대   가스라이팅 용어랑 상관없이 한남이 봊 후려치는거  영어단어 잘만 쓰면서 가스라이팅만 오글거리노  가스라이팅 오글거린다는 것도 가스라이팅임  아니근데 가스라이팅이란말 봊학식들 존나쓰는데  가스라이팅 싫으면 후려치기라고 해  가스라이팅 안당하려면 주위에 자랑같은거 하지마  가스라이팅을 일상에서 못쓴다는건 얼마나  쇼타 한명 가스라이팅해서 그루밍하고 싶긔  가스라이팅 오글거리는거랑 별개로 퍼지는게 봊한테 좋은건데  가스라이팅 같은게 퍼져야 최자같은 한남이 사리고다님  다른겅 몰라도 가스라이팅 맨스플레린 인플래이션이 오글거린단  가스라이팅은 성장기에 친구들한테 제일 많이 당하는것같음  맞노 빻순이짓 할때 가스라이팅 당했긔  김치국은 오지랖 라 가스라이팅이 일상이잖아  안토가 예섹 가스라이팅 해서 사겻으면 좋겟다  가스라이팅 노력한다고 안당하는거 아님  가스라이팅 아예 안당하는 사람 없음  누가 가스라이팅 시도하려고 할 때 참고하시긔  맞긔 가스라이팅 벗어나는법은 주관이 뚜렷하고  가스라이팅 어감이 너무 별로야  가스라이팅이고뭐고 그냥 만나고올때마다 기분찝찝하면 손절하는게 맞는듯  가스라이팅이라는 말 알려져서 좋은데  가스라이팅이 근본도없댄다  가스라이팅이라는 단어 혼모노같다는거   연예인들이 대부분 가스라이팅 잘당하는 그런유형의 사람들이 많음  빻은봊이 이쁜봊 가스라이팅하는것만큼 추한게 없긔  친구가 가스라이팅그게 친구노  가스라이팅 하는 새끼들 열에 아홉이  가스라이팅 잘당하는 피해자공통점이  가스라이팅 잘 당하는 사람들 특징이 뭐임  그얼굴로 가스라이팅 당한 숄 불쌍해  저 마귀할멈으로부터 윙족이 지키시긔 가스라이팅 당할라  망수 나가기 직전에 숄 보면 진짜 그 상폐남이 어떻게 가스라이팅을 했길래  잦만날때 가스라이팅 당하면 망가지긔  가스라이팅이 무슨 뜻이기  숄은 이쁜게문제가아니라 외모때문에 가스라이팅당하고  인지왜곡 시키는것 가스라이팅이긔  온냐들 잦중억 가스라이팅 하면서 호감표하는 잦알긔  읍나빛최잦 가스라이팅에 숄 좆예인인거  가스라이팅 당해서 정병심해진듯  띠니 급식때 가스라이팅당해서 씹찐따처럼 하고다녀서 찐따됐었는데  가스라이팅 썰 풀어보길래 쓴거야  약뱅노래 좋다는년들 읍죄기성적 언플에 가스라이팅 당한거야  종교는 애초부터 지배층이 가스라이팅 하는 용도였는데  가스라이팅이 모야  모성애 올려치는것도 가스라이팅임  텅텅뮤 가스라이팅 그만하시긔  김수미 할매한테 가스라이팅 당하는 대잦 내용 보고싶어  한남문학 종특은 봊 가스라이팅 안하면 연애 못함  뿡 근데 다들 가스라이팅 당하고 정병라 잘 꼬시면 띠니도 사귈수있을듯  남의식 약간 은따나 가스라이팅 많이 당하면 그렇게됨  언냐들 가스라이팅 조심해   휴메띠니 가스라이팅 하고싶긔  결혼하고 독박살림에 가스라이팅 존나 당한거면  저거도 구줌이 필터링한거 같긔 더 심한 말도 하면서 가스라이팅했노  구혜선 가스라이팅한 한국남자 면상  한녀들 와꾸 지나치게 안 보는 것도 가스라이팅 당한것 같아  년동안 남동충 가스라이팅시켜서 집안일떠맡겼긔  갓파 살때부터 납치해서 가스라이팅 존나 한다음에  흰수만 꾸니 트름랩에 가스라이팅 당하고 있나봐  가스라이팅 당하는 의뚝이  스스로 가스라이팅 미쳤노  뿡은 맨날 가스라이팅 하니까 허허충에 발작하는거긔  윽신이 봊친한테 가스라이팅 잘할거같음  일단 한남들이 만든 영화 모든게 다 봊들 가스라이팅시키고 기죽일려고  왜 좁이 주위엔 좁이 가스라이팅해줄 사람이 없을까  뿡 행복충아니긔 요새 가스라이팅당하고 불행충이었긔  찜 오늘 뮤뱅엔딩 영상으로 가스라이팅 오지게 당하겠노  삐에게 가스라이팅하는 한남 믂  딱쭈는 딱이가 쭈 가스라이팅 시도하다가  좁스부치언니 딱갤주 가스라이팅 성공한듯  김랩괴 가스라이팅 해서라도 갖고만다  딱이 좁이보고 코르셋조이라고 가스라이팅하다가  한녀들 그냥 단체로 정신병왓다니깐 하도 가스라이팅당해서  뿡는 가스라이팅 흙수저타령 명품백타령 안해서 좋긔  하괴윙족문학 가스라이팅  근데 한남한테 가스라이팅 당하면 존나좆같겟다  좁이 누가 가스라이팅 좀 해  혐애미들 존아 명잦이다 가스라이팅 중  짐승한테까지 가스라이팅 당해서 지 재산 쏟아붓는 병신년들  언냐 친구들이 가스라이팅하노  김주영 가스라이팅 최고긔  살면서 가스라이팅하고만 살아올것같은게 꾹인데  뿡은 꾹빼고 한남 가스라이팅 오져  언냐들 가스라이팅에 넘어가지좀 마시긔  서키 맘에드는 젊은 봊 있으면 가스라이팅 오지게했을듯  존나 능글거리면서 대놓고 가스라이팅하는 한남 존나싫어  가스라이팅 대놓고 하는 한남 볼때 존나 빡쳐  씹가위년들 한남 빙의해서 봊한테 가스라이팅 존나 해  띠니 가스라이팅 뜻 이제 알았오  퀸주영 가스라이팅   가스라이팅 하고싶어  가스라이팅 존나당하면 진짜 정신 이상해지는거같애  새내기시발련 가스라이팅 존나해서 좆생 망가뜨릴거야  가스라이팅이라는 단어랑 뿌주부랑 같은 문장에 잇는게 왤케 웃기지  뿌주부 가스라이팅 기술 라고 느꼇던거  가스라이팅깅  씹댕청한 잘생긴 잦 예쁜 봊 가스라이팅깅 하고싶기  가스라이팅이 뭐긔  띤갤언냐들 가스라이팅해서 띠니 시녀로 만들고싶긔  변요한띠니도 가스라이팅 당함  가스라이팅도 사랑인데 노무 왜곡하지는 마시긔  띠니는 가스라이팅과 사랑을 동일시하게 생각하긔  좆간대할때 이런생각 한번이라도 햇으면 가스라이팅 당한거야  가스라이팅 왕진진이 낸시랭한테도하던데  직장상사가 가스라이팅하는데 칼빵찌르고싶었긔  으누가 가스라이팅해주면 좋겠다 헌법으로 만들어야됨  가스라이팅 당하는년들 솔직히 지들도 알고잇긔  자기얘기만 안 해도 거의 가스라이팅 당할일 없긔  가스라이팅 당하는년들 특 분명 잘못해서 화냇는데 불안함  가스라이팅 유래 이거긔  가스라이팅 당사자말고 가해자일땐 진짜 존나재밋어  인싸새내기들 머갈통 쳐빻아서 가스라이팅해도 몰라  인싸새내기 씹입생들 가스라이팅 맨스플레인 하고싶긔  진짜 봊이면 대쉬 못받는다는것도 한남들 가스라이팅이긔  와꾸아니라도 빨거있는 새끼는 가스라이팅을 존나 해야됨  딱갤주가 좁깅이 머리로 후려치고 가스라이팅하는거 보고싶긔  제발 딱이가 좁이 옆에두고 가스라이팅 존나 했으면  똥미노 부랄에다 기름붓고 가스라이팅하고싶긔노윤딱  김경수 가스라이팅 존나 잘하게 생김  난 오히려 윰멍이 자기도 가스라이팅 피해자고  생각해보니까 윰댕도 김이브한테 가스라이팅당해서 몇년동안 끌려다녔잖아  좁이는 왜 가스라이팅도 안당하노  좁이 머리자르지말라는게 왜가스라이팅이긔  부니 머리로 가스라이팅 좀 당해야돼  머큐리 게이매니저가 가스라이팅 한거같은데  가스라이팅으로 흙수저 컨셉 잡아놓고 돈버니까 명품휘두르고다님  좁이 누가 가스라이팅 좀 하라고  앙준이 댕청해서 가스라이팅하고싶자나  트페미들아 니네 좌빨한테 가스라이팅 당한건 암  트페미들이 하는게 가스라이팅이긔  양아치 폰팔이 훈남한테 가스라이팅 당해서 동거하고 싶다  양남은 잦으로 안 보인다는것도 가스라이팅 당한거긔  한남친구한테 가스라이팅했는데  개독 가스라이팅인생 최후의 행복회로  봉랑이 가스라이팅 존나 잘할거같음  갓파 가스라이팅하기 최적화 아니긔  앙준이 가스라이팅 하면서 사귀고 싶어   한남들 가스라이팅해서 꼬무룩하게 만드는 법은   연하남 가스라이팅하면서 만나고싶긔  이오빠한테 가스라이팅 당하고싶다  근데 왜 한남새끼들은 와꾸도 고추도 좆빻은게 가스라이팅이 일상화되있음  가스라이팅하는방법  가스라이팅이고 지랄이고 작작싸워 미친년들아  트페미 시발년들 가스라이팅 뜻은 제대로 알고 말하는거노  내가 실제로봤던 가스라이팅 하나밖에없음  가스라이팅 좆돌새끼들한테 하면   가스라이팅 설명하는 년이 설명을 잘못했네  가스라이팅으로 한남패니까 이지랄난거잖아  가스라이팅플도 그냥 한마음으로 한남 패면 되는데  가스라이팅이 뭔데 가스에 불붙듯 서서히 유혹하는거임  가스라이팅이 걍 후려친다기 보다는 닌 나없으면  가스라이팅이라는건 정말 멍청하면 못하는짓인건 맞음  의견다른걸 억지로 세뇌시키는게 가스라이팅이라며  가스라이팅 영어단어있다니까 이거 이야 트페미용어아님  왜또 가스라이팅갤이냐 이기야  가스라이팅 얘기한지 얼마나됐다고 발작하는 이유가 뭐긔  트페미 시발년들아 니네가 가스라이팅 트리거를  서창빈 가스라이팅 해서 은퇴시키고 싶다  가스라이팅 좌좀들이잘함  가스라이팅 당했네 이러는거 솔직히 폭토커가 지 싸패라 그러는거 보는 기분  새끼 가스라이팅하고싶다  가스라이팅이라는 단어에 발작하는 이유  나 좆이콘한테 가스라이팅 당햇긔  가스라이팅은 후려치기랑은 조금 다른느낌  맨날 앰한테 가스라이팅당하는데 자존감 안떨어짐  김치국에서 가스라이팅 안 당하는 봊이 없을텐데  가스라이팅 이지랄하는거 존나 트페미같다  가스라이팅말고 동숲갤하자  가스라이팅인가 그딴거 미자때 아님 당하는거 존나 이해안됨  가스라이팅말고 다른말없노 존나 트페미같아  왜 갑자기 가스라이팅 갤이긔  가스라이팅이 뭔데  전라도 남자들이 가스라이팅을 잘함  가스라이팅이 존나 무서운게 봊이 뒤질때까지 쳐맞고도  글고 가스라이팅이 진짜 무서운게 어떻게 그 무리에서  잦친한테 가스라이팅 당하는 봊도 진짜 이상한게  우리나라 전체가 봊상대로 가스라이팅 한다는거 맞음  가스라이팅하는 한남들 강약약강임  가스라이팅 걸릴 새끼만 걸린단건 뻘소리긔  가스라이팅 방법중에 하나 이거라하긩  존나 가까운 사람이 가스라이팅 했다고 생각해봐  가스라이팅 저거 어원도 만 걸려드는거 맞네  가스라이팅이 머임 나도 할래  존나긴반고닉이 나한테 자꾸 시비거는것도 가스라이팅이긔  호모문학에 트리거 가스라이팅 이러는거 존나같잖아  가스라이팅 우리애미가 존나잘해  가스라이팅 어원 존나 소름돋긔  가스라이팅도 당해본 사람이 잘함  가스라이팅 동등한관계보다 수직관계에서 잘먹힐듯  가스라이팅이 페미용어래도 저정도는 인식하고 있어야하긔  가스라이팅에서 벗어나는건 쉬울거같음  가스라이팅 자존감낮은 머리좋은애들이잘함  가스라이팅 트페미용어 맞음  가스라이팅 존나 잘하는 년들이 있긔  저 태국똥냐옵 구해줘야 되는 거 아님 가스라이팅 당하는 중인 것 같아  시녀들 지가빠는 봊돌 라고 가스라이팅 시동거는거 토나와  보다보면 잘생겼다 이거 착즙이나 가스라이팅 둘 중하나임  마시도 그렇고 안토도 그렇고 나는 꾸며도 안된다고 가스라이팅 된 봊들 불쌍해  으누가 가스라이팅 하는건 그냥 사랑이지  은우한테 가스라이팅 당하고 싶어  으누한테는 가스라이팅 당하고 싶어  난 은오후 가스라이팅 하고싶긔  앙준이 가스라이팅하고싶어  가스라이팅 호모웹툰없노  방탄 아미한테 가스라이팅 오지게 하네  며느리에게 가하는 가스라이팅  가스라이팅 예시 아는 사람  친구년 하는 짓 가스라이팅 맞지  나 가스라이팅 해봐  이것도 가스라이팅이라고 할   가스라이팅 당하는 거 같아요  상식 가스라이팅에 대해서 알아보자 똑똑한 병신들만 클릭 
"""

In [385]:
t = Tokenizer()
t.fit_on_texts([text1])
vocab_size = len(t.word_index) + 1
# 케라스 토크나이저의 정수 인코딩은 인덱스가 1부터 시작하지만,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야하므로 미리 +1 선언 
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 1581


In [386]:
text3 = list()
for line in text1.split('  '):
    text3.append(line)

In [389]:
encoded = t.texts_to_sequences([text3[0]])[0]
encoded

[291, 292, 18, 293, 294]

In [387]:
sequences = list()
for line in text3: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[(len(encoded)-i-1):]
        sequences.append(sequence)

len(sequences)

2076

In [364]:
sequences

[[293, 294],
 [18, 293, 294],
 [292, 18, 293, 294],
 [291, 292, 18, 293, 294],
 [1, 42],
 [299, 1, 42],
 [298, 299, 1, 42],
 [297, 298, 299, 1, 42],
 [296, 297, 298, 299, 1, 42],
 [295, 296, 297, 298, 299, 1, 42],
 [301, 302],
 [1, 301, 302],
 [120, 1, 301, 302],
 [72, 120, 1, 301, 302],
 [119, 72, 120, 1, 301, 302],
 [300, 119, 72, 120, 1, 301, 302],
 [305, 306],
 [304, 305, 306],
 [303, 304, 305, 306],
 [122, 303, 304, 305, 306],
 [121, 122, 303, 304, 305, 306],
 [309, 310],
 [308, 309, 310],
 [307, 308, 309, 310],
 [312, 73],
 [24, 312, 73],
 [1, 24, 312, 73],
 [311, 1, 24, 312, 73],
 [2, 316],
 [315, 2, 316],
 [1, 315, 2, 316],
 [314, 1, 315, 2, 316],
 [313, 314, 1, 315, 2, 316],
 [318, 319],
 [317, 318, 319],
 [74, 124],
 [24, 74, 124],
 [1, 24, 74, 124],
 [123, 1, 24, 74, 124],
 [321, 322],
 [10, 321, 322],
 [320, 10, 321, 322],
 [326, 327],
 [325, 326, 327],
 [324, 325, 326, 327],
 [1, 324, 325, 326, 327],
 [1, 1, 324, 325, 326, 327],
 [323, 1, 1, 324, 325, 326, 327],
 [1, 42],


In [367]:
max_len=max(len(l) for l in sequences)
sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

In [368]:
sequences

array([[ 293,  294,    0, ...,    0,    0,    0],
       [  18,  293,  294, ...,    0,    0,    0],
       [ 292,   18,  293, ...,    0,    0,    0],
       ...,
       [1576, 1577, 1578, ...,    0,    0,    0],
       [  21, 1576, 1577, ...,    0,    0,    0],
       [1575,   21, 1576, ...,    0,    0,    0]])

In [369]:
r_sequences = np.array(r_sequences)
X = sequences[:,1:]
y = sequences[:,:1]

In [370]:
X

array([[ 294,    0,    0, ...,    0,    0,    0],
       [ 293,  294,    0, ...,    0,    0,    0],
       [  18,  293,  294, ...,    0,    0,    0],
       ...,
       [1577, 1578, 1579, ...,    0,    0,    0],
       [1576, 1577, 1578, ...,    0,    0,    0],
       [  21, 1576, 1577, ...,    0,    0,    0]])

In [371]:
y

array([[ 293],
       [  18],
       [ 292],
       ...,
       [1576],
       [  21],
       [1575]])

In [372]:
y = to_categorical(y, num_classes=vocab_size)

In [373]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 10
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, verbose=2)

Epoch 1/150
65/65 - 1s - loss: 7.0307 - accuracy: 0.1450
Epoch 2/150
65/65 - 1s - loss: 6.3077 - accuracy: 0.1527
Epoch 3/150
65/65 - 1s - loss: 6.0889 - accuracy: 0.1532
Epoch 4/150
65/65 - 1s - loss: 5.9380 - accuracy: 0.1532
Epoch 5/150
65/65 - 1s - loss: 5.8302 - accuracy: 0.1532
Epoch 6/150
65/65 - 1s - loss: 5.7490 - accuracy: 0.1532
Epoch 7/150
65/65 - 1s - loss: 5.6805 - accuracy: 0.1532
Epoch 8/150
65/65 - 1s - loss: 5.6107 - accuracy: 0.1537
Epoch 9/150
65/65 - 1s - loss: 5.5157 - accuracy: 0.1527
Epoch 10/150
65/65 - 1s - loss: 5.4475 - accuracy: 0.1527
Epoch 11/150
65/65 - 1s - loss: 5.3816 - accuracy: 0.1541
Epoch 12/150
65/65 - 1s - loss: 5.3278 - accuracy: 0.1566
Epoch 13/150
65/65 - 1s - loss: 5.2388 - accuracy: 0.1580
Epoch 14/150
65/65 - 1s - loss: 5.1360 - accuracy: 0.1604
Epoch 15/150
65/65 - 1s - loss: 5.0668 - accuracy: 0.1657
Epoch 16/150
65/65 - 1s - loss: 4.9902 - accuracy: 0.1638
Epoch 17/150
65/65 - 1s - loss: 4.8833 - accuracy: 0.1667
Epoch 18/150
65/65 - 1s

Epoch 142/150
65/65 - 1s - loss: 1.3163 - accuracy: 0.5771
Epoch 143/150
65/65 - 1s - loss: 1.2940 - accuracy: 0.5867
Epoch 144/150
65/65 - 1s - loss: 1.2808 - accuracy: 0.5978
Epoch 145/150
65/65 - 1s - loss: 1.2596 - accuracy: 0.6069
Epoch 146/150
65/65 - 1s - loss: 1.2638 - accuracy: 0.6045
Epoch 147/150
65/65 - 1s - loss: 1.2655 - accuracy: 0.5959
Epoch 148/150
65/65 - 1s - loss: 1.2209 - accuracy: 0.6021
Epoch 149/150
65/65 - 1s - loss: 1.1922 - accuracy: 0.6272
Epoch 150/150
65/65 - 1s - loss: 1.1409 - accuracy: 0.6537


In [374]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=11, padding='post') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word =  current_word + ' '  + word  # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word  # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [376]:
print(sentence_generation(model, t, '가스라이팅', 4))

가스라이팅 단체여야한다고 열에 윰댕도 전라도


In [379]:
encoded = t.texts_to_sequences(['가스라이팅'])[0] 

In [382]:
encoded = t.texts_to_sequences(['가스라이팅 단체여야한다고 '])[0] 

In [383]:
encoded

[1, 152]

In [380]:
pad_sequences([encoded], maxlen=11, padding='post')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])